param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$ProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
$source = Join-Path $ProjectRoot 'assets/source/intro/cinematic-lave.png'
$preview = Join-Path $ProjectRoot 'assets/preview/intro/main-menu-background-native.png'
$header = Join-Path $ProjectRoot 'src/intro-art.h'
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $preview) | Out-Null

$drawingReferences = @([System.Drawing.Bitmap].Assembly.Location, [System.Drawing.Rectangle].Assembly.Location) | Select-Object -Unique
$drawingReferences += @([AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.FullName -match '^System.Private.Windows.' } | ForEach-Object { $_.Location })
Add-Type -ReferencedAssemblies $drawingReferences -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
public static class IntroArtCompiler {
 static Bitmap Cover(Bitmap source,int width,int height){
  double sourceRatio=source.Width/(double)source.Height,targetRatio=width/(double)height;
  Rectangle crop;
  if(sourceRatio>targetRatio){int cw=(int)Math.Round(source.Height*targetRatio);crop=new Rectangle((source.Width-cw)/2,0,cw,source.Height);}
  else {int ch=(int)Math.Round(source.Width/targetRatio);crop=new Rectangle(0,(source.Height-ch)/2,source.Width,ch);}
  Bitmap output=new Bitmap(width,height,PixelFormat.Format32bppArgb);
  for(int y=0;y<height;y++)for(int x=0;x<width;x++){
   int sx=crop.Left+(int)(((long)x*2+1)*crop.Width/(width*2));
   int sy=crop.Top+(int)(((long)y*2+1)*crop.Height/(height*2));
   Color c=source.GetPixel(Math.Min(crop.Right-1,sx),Math.Min(crop.Bottom-1,sy));
   int r=c.R>>3,g=c.G>>3,b=c.B>>3;
   output.SetPixel(x,y,Color.FromArgb(255,(r<<3)|(r>>2),(g<<3)|(g>>2),(b<<3)|(b>>2)));
  }
  return output;
 }
 static void WritePixels(StreamWriter writer,Bitmap image){int n=0;for(int y=0;y<image.Height;y++)for(int x=0;x<image.Width;x++){
  Color c=image.GetPixel(x,y);int value=0x8000|((c.R>>3)<<10)|((c.G>>3)<<5)|(c.B>>3);
  if((n&15)==0)writer.Write("  ");writer.Write("0x"+value.ToString("X4")+",");if((++n&15)==0)writer.WriteLine();
 }if((n&15)!=0)writer.WriteLine();}
 public static void Compile(string source,string preview,string header){
  using(Bitmap original=new Bitmap(source))using(Bitmap image=Cover(original,480,272)){
   using(StreamWriter writer=new StreamWriter(header,false)){writer.NewLine="\n";
    writer.WriteLine("/* Generated by tools/bake-intro-art.ps1; authored main-menu plate in ARGB1555. */");
    writer.WriteLine("#ifndef ELITE_INTRO_ART_H\n#define ELITE_INTRO_ART_H\n#include <stdint.h>");
    writer.WriteLine("#define INTRO_BACKDROP_W 480\n#define INTRO_BACKDROP_H 272");
    writer.WriteLine("static const uint16_t intro_backdrop[130560]={");WritePixels(writer,image);writer.WriteLine("};\n#endif");
   }
   image.Save(preview,ImageFormat.Png);
  }
 }
}
'@
[IntroArtCompiler]::Compile($source,$preview,$header)
Write-Output "Compiled $header"
