$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$root=Split-Path $PSScriptRoot
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;using System.Drawing;using System.IO;using System.Text;using System.Text.RegularExpressions;
public static class FaunaAnimationBake {
 public static void Run(string root){
  var matches=Regex.Matches(File.ReadAllText(Path.Combine(root,"src/generated/field-wildlife-pixels.h")),@"RGB\((\d+),(\d+),(\d+)\)");
  var pal=new Color[64];for(int i=0;i<64;i++)pal[i]=Color.FromArgb(int.Parse(matches[i].Groups[1].Value),int.Parse(matches[i].Groups[2].Value),int.Parse(matches[i].Groups[3].Value));
  Directory.CreateDirectory(Path.Combine(root,"assets/generated/fauna-animation"));
  using(var src=new Bitmap(Path.Combine(root,"assets/source/fauna-animation/poses.png")))
  using(var preview=new Bitmap(192,512)){
   var output=new StringBuilder("/* Generated by tools/bake-fauna-animation.ps1. Shared 64-colour field palette. */\nstatic const unsigned char fauna_anim_pixels[8][4][3072]={\n");
   for(int family=0;family<8;family++){
    int[] bx=new int[4],by=new int[4],ex=new int[4],ey=new int[4];int mw=1,mh=1;
    for(int frame=0;frame<4;frame++){
     int x0=frame*src.Width/4,x1=(frame+1)*src.Width/4,y0=family*src.Height/8,y1=(family+1)*src.Height/8;bx[frame]=x1;by[frame]=y1;ex[frame]=x0;ey[frame]=y0;
     for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)if(src.GetPixel(x,y).A>160){bx[frame]=Math.Min(bx[frame],x);by[frame]=Math.Min(by[frame],y);ex[frame]=Math.Max(ex[frame],x);ey[frame]=Math.Max(ey[frame],y);}
     if(bx[frame]>ex[frame]||by[frame]>ey[frame])throw new Exception("Empty animation cell");
     mw=Math.Max(mw,ex[frame]-bx[frame]+1);mh=Math.Max(mh,ey[frame]-by[frame]+1);
    }
    double scale=Math.Min(46.0/mw,61.0/mh);output.Append("{\n");
    for(int frame=0;frame<4;frame++){
     int dw=Math.Max(1,(int)Math.Round((ex[frame]-bx[frame]+1)*scale)),dh=Math.Max(1,(int)Math.Round((ey[frame]-by[frame]+1)*scale)),ox=(48-dw)/2,oy=64-dh;output.Append("{\n");
     for(int y=0;y<64;y++)for(int x=0;x<48;x++){
      int index=255;
      if(x>=ox&&x<ox+dw&&y>=oy){int sx=bx[frame]+Math.Min(ex[frame]-bx[frame],(int)((x-ox+.5)/scale)),sy=by[frame]+Math.Min(ey[frame]-by[frame],(int)((y-oy+.5)/scale));Color c=src.GetPixel(sx,sy);
       if(c.A>160){int best=int.MaxValue;for(int i=0;i<64;i++){int dr=c.R-pal[i].R,dg=c.G-pal[i].G,db=c.B-pal[i].B,d=2*dr*dr+3*dg*dg+db*db;if(d<best){best=d;index=i;}}preview.SetPixel(frame*48+x,family*64+y,pal[index]);}}
      output.Append(index).Append(',');if(x==47)output.Append('\n');
     }output.Append("},\n");
    }output.Append("},\n");
   }output.Append("};\n");File.WriteAllText(Path.Combine(root,"src/generated/fauna-animation-pixels.h"),output.ToString(),new UTF8Encoding(false));
   preview.Save(Path.Combine(root,"assets/generated/fauna-animation/poses.png"),System.Drawing.Imaging.ImageFormat.Png);
  }
 }
}
'@
[FaunaAnimationBake]::Run($root)
