"""Bake the transparent Mira Vale presenter into the native ARGB1555 format."""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source = root / "assets" / "source" / "local-tv-mira.png"
out = root / "src" / "local-tv-mira.h"
image = Image.open(source).convert("RGBA")
alpha = image.getchannel("A")
box = alpha.getbbox()
if not box:
    raise SystemExit("Mira sprite has no opaque pixels")
image = image.crop(box)
scale = min(96 / image.width, 128 / image.height)
image = image.resize((max(1, int(image.width * scale)), max(1, int(image.height * scale))), Image.Resampling.NEAREST)
canvas = Image.new("RGBA", (96, 128), (0, 0, 0, 0))
canvas.paste(image, ((96 - image.width) // 2, (128 - image.height) // 2), image)

values = []
for r, g, b, a in canvas.getdata():
    if a < 128:
        values.append(0)
    else:
        values.append(0x8000 | ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3))

lines = [
    "/* Generated by tools/bake-local-tv-mira.py; ARGB1555 with alpha bit. */",
    "#include <stdint.h>",
    "#define LOCAL_TV_MIRA_W 96",
    "#define LOCAL_TV_MIRA_H 128",
    "static const uint16_t local_tv_mira[LOCAL_TV_MIRA_W*LOCAL_TV_MIRA_H] = {",
]
for i in range(0, len(values), 16):
    lines.append("  " + ",".join(f"0x{v:04X}" for v in values[i:i + 16]) + ",")
lines += ["};", ""]
out.write_text("\n".join(lines), encoding="ascii")
print(f"Baked {out} ({image.width}x{image.height} source fit into 96x128)")
