$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$root=Split-Path $PSScriptRoot
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;using System.Drawing;using System.IO;using System.Text;
public static class FieldWildlifeBake {
 static readonly string[] Hex={"07140f","102319","1a3820","25502a","326b32","43863a","5d9f42","7bb54a","a5ca56","d5dc70","312820","483526","66472f","805936","a17547","c69255","e1b976","162e2c","26504a","367766","649382","9ca58b","c2c5a3","e0dfbd","56616a","76818b","a1a8aa","d3d1bc","bd7b38","e8a838","ffd663","eaf2d0","191925","30283e","4b3556","684666","865678","ac7495","d39bad","efc5c6","173c42","235760","327b80","569c99","84b8ac","c0d9c5","252c46","354565","4c6989","7093ac","a3c1d0","dfedf0","694423","9c6835","c7904a","edb768","eddba8","b1a181","837357","514634","643935","91594c","bf8268","edb598"};
 public static void Run(string root){
  var pal=new Color[64];for(int i=0;i<64;i++)pal[i]=ColorTranslator.FromHtml("#"+Hex[i]);
  Directory.CreateDirectory(Path.Combine(root,"assets/generated/field-wildlife"));
  using(var src=new Bitmap(Path.Combine(root,"assets/source/field-wildlife/species-atlas.png")))
  using(var preview=new Bitmap(192,256)){
   var h=new StringBuilder("/* Generated by tools/bake-field-wildlife.ps1. 16 shared 48x64 sprites, transparent index 255. */\nstatic const unsigned field_art_palette[64]={\n");
   foreach(var c in pal)h.AppendFormat("RGB({0},{1},{2}),",c.R,c.G,c.B);
   h.Append("\n};\nstatic const unsigned char field_art_pixels[16][3072]={\n");
   for(int cell=0;cell<16;cell++){
    int x0=cell%4*src.Width/4,y0=cell/4*src.Height/4,x1=(cell%4+1)*src.Width/4,y1=(cell/4+1)*src.Height/4,bx=x1,by=y1,ex=x0,ey=y0;
    for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)if(src.GetPixel(x,y).A>160){bx=Math.Min(bx,x);by=Math.Min(by,y);ex=Math.Max(ex,x);ey=Math.Max(ey,y);}
    if(ex<bx||ey<by)throw new Exception("Empty species cell "+cell);
    double scale=Math.Min(46.0/(ex-bx+1),61.0/(ey-by+1));int dw=Math.Max(1,(int)Math.Round((ex-bx+1)*scale)),dh=Math.Max(1,(int)Math.Round((ey-by+1)*scale)),ox=(48-dw)/2,oy=64-dh;
    h.Append("{\n");
    for(int y=0;y<64;y++)for(int x=0;x<48;x++){
     int index=255;
     if(x>=ox&&x<ox+dw&&y>=oy){int sx=bx+Math.Min(ex-bx,(int)((x-ox+.5)*(ex-bx+1)/dw)),sy=by+Math.Min(ey-by,(int)((y-oy+.5)*(ey-by+1)/dh));var c=src.GetPixel(sx,sy);if(c.A>160){int dist=int.MaxValue;for(int i=0;i<64;i++){int dr=c.R-pal[i].R,dg=c.G-pal[i].G,db=c.B-pal[i].B,d=2*dr*dr+3*dg*dg+db*db;if(d<dist){dist=d;index=i;}}preview.SetPixel(cell%4*48+x,cell/4*64+y,pal[index]);}}
     h.Append(index).Append(',');if(x==47)h.Append('\n');
    }h.Append("},\n");
   }h.Append("};\n");
   File.WriteAllText(Path.Combine(root,"src/generated/field-wildlife-pixels.h"),h.ToString(),new UTF8Encoding(false));
   preview.Save(Path.Combine(root,"assets/generated/field-wildlife/species-atlas.png"),System.Drawing.Imaging.ImageFormat.Png);
  }
 }
}
'@
[FieldWildlifeBake]::Run($root)
Write-Output 'Baked 16 species: 48 KiB indexed pixels, 64 shared colours.'
