"""Bake the authored 4x3 pulp portrait sheet into native PSP ARGB1555 tiles."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/portrait-atlas.h"
TILE = 64
SHEETS = (
    ("pulp-humans-16.png", 4, 4),
    ("pulp-orrith-amphibian-16.png", 4, 4),
    ("pulp-insect-sauran-16.png", 4, 4),
    ("pulp-avian-masked-16.png", 4, 4),
    ("pulp-robots-12.png", 4, 3),
    ("pulp-androids-12.png", 4, 3),
    ("pulp-crystal-fungal-8.png", 4, 2),
)


def argb1555(pixel):
    r, g, b, a = pixel
    if a < 64:
        return 0
    return 0x8000 | ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)


tiles = []
for filename, cols, rows in SHEETS:
    image = Image.open(ROOT / "assets/source/portraits" / filename).convert("RGBA")
    for row in range(rows):
        for col in range(cols):
            box = (
                col * image.width // cols,
                row * image.height // rows,
                (col + 1) * image.width // cols,
                (row + 1) * image.height // rows,
            )
            tile = image.crop(box).resize((TILE, TILE), Image.Resampling.NEAREST)
            tiles.append([argb1555(pixel) for pixel in tile.getdata()])

lines = [
    "/* Generated by tools/bake-portrait-atlas.py. Do not hand-edit. */",
    "#ifndef ELITE_PULP_PORTRAIT_ATLAS_H",
    "#define ELITE_PULP_PORTRAIT_ATLAS_H",
    f"enum {{ PORTRAIT_PULP_TILE=64, PORTRAIT_PULP_BASE_COUNT={len(tiles)} }};",
    "static const uint16_t portrait_pulp_bases[PORTRAIT_PULP_BASE_COUNT][4096]={",
]
for index, data in enumerate(tiles):
    lines.append(" {")
    for start in range(0, len(data), 16):
        lines.append("  " + ",".join(f"0x{value:04X}" for value in data[start:start + 16]) + ",")
    lines.append(" },")
lines.extend(("};", "#endif", ""))
OUTPUT.write_text("\n".join(lines), encoding="ascii")
print(f"baked {len(tiles)} portraits from {len(SHEETS)} sheets to {OUTPUT}")
