"""Palette-bake generated alpha props to embedded PSP cells."""
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[1]
src = Image.open(root / 'assets/source/biome-props/kit-alpha.png').convert('RGBA')
cells = []
for row in range(6):
    for col in range(4):
        cell = src.crop((col*src.width//4,row*src.height//6,(col+1)*src.width//4,(row+1)*src.height//6))
        mask = cell.getchannel('A').point(lambda a: 255 if a > 160 else 0)
        bounds = mask.getbbox()
        if not bounds:
            raise ValueError('Empty prop')
        prop = cell.crop(bounds)
        prop.thumbnail((46,62),Image.Resampling.NEAREST)
        out = Image.new('RGBA',(48,64))
        out.paste(prop,((48-prop.width)//2,64-prop.height))
        cells.append(out)
sheet = Image.new('RGBA',(192,384))
for i,cell in enumerate(cells):
    sheet.paste(cell,(i%4*48,i//4*64))
opaque = Image.new('RGB',sheet.size,(45,48,50))
opaque.paste(sheet,mask=sheet.getchannel('A'))
indexed = opaque.quantize(colors=128,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
palette = indexed.getpalette()[:384]
lines = ['/* Generated by tools/bake-biome-props.py. */','static const unsigned biome_prop_palette[128]={']
lines += [f'RGB({palette[i]},{palette[i+1]},{palette[i+2]}),' for i in range(0,384,3)]
lines += ['};','static const unsigned char biome_prop_pixels[24][3072]={']
for i in range(24):
    lines.append('{')
    for y in range(64):
        lines.append(','.join(str(indexed.getpixel((i%4*48+x,i//4*64+y))) if cells[i].getpixel((x,y))[3]>160 else '255' for x in range(48))+',')
    lines.append('},')
lines.append('};')
(root/'src/generated/biome-props-pixels.h').write_text('\n'.join(lines)+'\n')
dest=root/'assets/generated/biome-props'
dest.mkdir(parents=True,exist_ok=True)
sheet.save(dest/'kit.png')
print('24 transparent cells; 73728 indexed bytes')
