# Convert AI pixel-art PNGs into chroma-keyed C arrays for the PSP blit.
param(
  [string]$Assets = "C:\Users\skarm\.cursor\projects\c-Users-skarm-Documents-Codex-2026-09-14-let\assets",
  [string]$Out = "C:\Users\skarm\Documents\Codex\2026-09-14\let\outputs\arcelite-psp\src\sprites.h"
)
Add-Type -AssemblyName System.Drawing
function Test-Magenta([Drawing.Color]$c) {
  return ($c.R -gt 190 -and $c.B -gt 190 -and $c.G -lt 110)
}
function Get-Crop([Drawing.Bitmap]$bmp) {
  $x0 = $bmp.Width; $y0 = $bmp.Height; $x1 = -1; $y1 = -1
  for ($y = 0; $y -lt $bmp.Height; $y++) {
    for ($x = 0; $x -lt $bmp.Width; $x++) {
      if (-not (Test-Magenta $bmp.GetPixel($x, $y))) {
        if ($x -lt $x0) { $x0 = $x }
        if ($y -lt $y0) { $y0 = $y }
        if ($x -gt $x1) { $x1 = $x }
        if ($y -gt $y1) { $y1 = $y }
      }
    }
  }
  if ($x1 -lt 0) { return [Drawing.Rectangle]::FromLTRB(0, 0, $bmp.Width, $bmp.Height) }
  return [Drawing.Rectangle]::FromLTRB($x0, $y0, $x1 + 1, $y1 + 1)
}
function Convert-Sprite([string]$path, [int]$maxW, [int]$maxH) {
  $src = [Drawing.Bitmap]::FromFile($path)
  $box = Get-Crop $src
  $cropped = $src.Clone($box, $src.PixelFormat)
  $scale = [Math]::Min($maxW / [double]$cropped.Width, $maxH / [double]$cropped.Height)
  $w = [Math]::Max(8, [int][Math]::Round($cropped.Width * $scale))
  $h = [Math]::Max(8, [int][Math]::Round($cropped.Height * $scale))
  $dst = New-Object Drawing.Bitmap $w, $h
  $g = [Drawing.Graphics]::FromImage($dst)
  $g.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
  $g.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::Half
  $g.DrawImage($cropped, 0, 0, $w, $h)
  $g.Dispose()
  $pixels = New-Object System.Collections.Generic.List[string]
  for ($y = 0; $y -lt $h; $y++) {
    for ($x = 0; $x -lt $w; $x++) {
      $c = $dst.GetPixel($x, $y)
      if (Test-Magenta $c) { $pixels.Add("0") }
      else { $pixels.Add(("0x{0:X8}u" -f ([uint32]($c.R -bor ($c.G -shl 8) -bor ($c.B -shl 16) -bor 0xFF000000)))) }
    }
  }
  $src.Dispose(); $cropped.Dispose(); $dst.Dispose()
  return @{ W = $w; H = $h; Pixels = $pixels }
}
$jobs = @(
  @{ Name = "pad"; File = "psp-3000-pixel.png"; W = 212; H = 118 },
  @{ Name = "planet"; File = "icon-planet.png"; W = 32; H = 32 },
  @{ Name = "ship"; File = "icon-ship.png"; W = 32; H = 32 },
  @{ Name = "system"; File = "icon-system.png"; W = 32; H = 32 },
  @{ Name = "station"; File = "icon-station.png"; W = 32; H = 32 }
)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Baked 16-bit AI sprites. Magenta chroma is 0. Regenerated by tools/bake-sprites.ps1 */")
[void]$sb.AppendLine("static void blit_spr(int x,int y,int w,int h,const unsigned *p){for(int j=0;j<h;j++)for(int i=0;i<w;i++){unsigned c=p[j*w+i];if(c)pixel(x+i,y+j,c);}}")
foreach ($job in $jobs) {
  $spr = Convert-Sprite (Join-Path $Assets $job.File) $job.W $job.H
  [void]$sb.AppendLine(("enum { SPR_{0}_W={1}, SPR_{0}_H={2} };" -f $job.Name.ToUpper(), $spr.W, $spr.H))
  [void]$sb.AppendLine(("static const unsigned spr_{0}[]={{" -f $job.Name))
  $line = New-Object System.Collections.Generic.List[string]
  for ($i = 0; $i -lt $spr.Pixels.Count; $i++) {
    $line.Add($spr.Pixels[$i])
    if ($line.Count -eq 12) {
      [void]$sb.AppendLine((" {0}," -f ($line -join ",")))
      $line.Clear()
    }
  }
  if ($line.Count) { [void]$sb.AppendLine((" {0}" -f ($line -join ","))) }
  [void]$sb.AppendLine("};")
}
[System.IO.File]::WriteAllText($Out, $sb.ToString())
Write-Output "Wrote $Out"
