param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$ProjectRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
$source = Join-Path $ProjectRoot 'assets/source/system-almanac'
$preview = Join-Path $ProjectRoot 'assets/preview/system-almanac'
$header = Join-Path $ProjectRoot 'src/system-almanac-art.h'
New-Item -ItemType Directory -Force -Path $preview | Out-Null

$drawingReferences = @([System.Drawing.Bitmap].Assembly.Location, [System.Drawing.Rectangle].Assembly.Location) | Select-Object -Unique
$drawingReferences += @([AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.FullName -match '^System.Private.Windows.' } | ForEach-Object { $_.Location })
Add-Type -ReferencedAssemblies $drawingReferences -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
public static class AlmanacArtCompiler {
 static Rectangle AlphaBounds(Bitmap image,Rectangle cell) {
  int l=cell.Right,t=cell.Bottom,r=-1,b=-1;
  for(int y=cell.Top;y<cell.Bottom;y++)for(int x=cell.Left;x<cell.Right;x++)if(image.GetPixel(x,y).A>=128){if(x<l)l=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}
  if(r<l||b<t)throw new InvalidDataException("Empty station cell");
  return Rectangle.FromLTRB(l,t,r+1,b+1);
 }
 static Bitmap Resize(Bitmap source,Rectangle crop,int width,int height,bool contain) {
  Bitmap output=new Bitmap(width,height,PixelFormat.Format32bppArgb);
  int dw=width,dh=height,ox=0,oy=0;
  if(contain){double s=Math.Min(width/(double)crop.Width,height/(double)crop.Height);dw=Math.Max(1,(int)Math.Floor(crop.Width*s));dh=Math.Max(1,(int)Math.Floor(crop.Height*s));ox=(width-dw)/2;oy=(height-dh)/2;}
  for(int y=0;y<dh;y++)for(int x=0;x<dw;x++){
   int sx=crop.Left+(int)(((long)x*2+1)*crop.Width/(dw*2));
   int sy=crop.Top+(int)(((long)y*2+1)*crop.Height/(dh*2));
   Color c=source.GetPixel(Math.Min(crop.Right-1,sx),Math.Min(crop.Bottom-1,sy));
   if(c.A<128)continue;
   int r=c.R>>3,g=c.G>>3,b=c.B>>3;
   output.SetPixel(ox+x,oy+y,Color.FromArgb(255,(r<<3)|(r>>2),(g<<3)|(g>>2),(b<<3)|(b>>2)));
  }
  return output;
 }
 static void WritePixels(StreamWriter writer,Bitmap image){int n=0;for(int y=0;y<image.Height;y++)for(int x=0;x<image.Width;x++){
  Color c=image.GetPixel(x,y);int v=c.A<128?0:0x8000|((c.R>>3)<<10)|((c.G>>3)<<5)|(c.B>>3);
  if((n&15)==0)writer.Write("  ");writer.Write("0x"+v.ToString("X4")+",");if((++n&15)==0)writer.WriteLine();
 }if((n&15)!=0)writer.WriteLine();}
 static void WriteArray(StreamWriter writer,string name,Bitmap image){writer.WriteLine("static const uint16_t "+name+"["+(image.Width*image.Height)+"]={");WritePixels(writer,image);writer.WriteLine("};");}
 public static void Compile(string source,string preview,string header){
  using(Bitmap bg=new Bitmap(Path.Combine(source,"starfield.png")))
  using(Bitmap stations=new Bitmap(Path.Combine(source,"stations.png")))
  using(Bitmap sunSource=new Bitmap(Path.Combine(source,"sun.png")))
  using(Bitmap backdrop=Resize(bg,new Rectangle(0,0,bg.Width,bg.Height),294,193,false)){
   /* Transparent gutters in the authored sheet are part of its contract. */
   Rectangle a=AlphaBounds(stations,Rectangle.FromLTRB(0,0,350,stations.Height));
   Rectangle b=AlphaBounds(stations,Rectangle.FromLTRB(350,0,1050,stations.Height));
   Rectangle c=AlphaBounds(stations,Rectangle.FromLTRB(1050,0,stations.Width,stations.Height));
   Rectangle sunBounds=AlphaBounds(sunSource,new Rectangle(0,0,sunSource.Width,sunSource.Height));
   using(Bitmap poor=Resize(stations,a,64,58,true))
   using(Bitmap rich=Resize(stations,b,118,76,true))
   using(Bitmap mega=Resize(stations,c,150,96,true))
   using(Bitmap sun=Resize(sunSource,sunBounds,154,154,true)){
    using(StreamWriter writer=new StreamWriter(header,false)){writer.NewLine="\n";
     writer.WriteLine("/* Generated by tools/bake-system-almanac.ps1; authored project pixel art in ARGB1555. */");
     writer.WriteLine("#ifndef ELITE_SYSTEM_ALMANAC_ART_H\n#define ELITE_SYSTEM_ALMANAC_ART_H\n#include <stdint.h>");
     writer.WriteLine("#define ALMANAC_BACKDROP_W 294\n#define ALMANAC_BACKDROP_H 193");
     writer.WriteLine("#define ALMANAC_SUN_W 154\n#define ALMANAC_SUN_H 154");
     writer.WriteLine("#define ALMANAC_POOR_W 64\n#define ALMANAC_POOR_H 58\n#define ALMANAC_RICH_W 118\n#define ALMANAC_RICH_H 76\n#define ALMANAC_MEGA_W 150\n#define ALMANAC_MEGA_H 96");
     WriteArray(writer,"almanac_backdrop",backdrop);WriteArray(writer,"almanac_sun",sun);WriteArray(writer,"almanac_station_poor",poor);WriteArray(writer,"almanac_station_rich",rich);WriteArray(writer,"almanac_station_mega",mega);
     writer.WriteLine("#endif");
    }
    backdrop.Save(Path.Combine(preview,"backdrop-native.png"),ImageFormat.Png);sun.Save(Path.Combine(preview,"sun-native.png"),ImageFormat.Png);poor.Save(Path.Combine(preview,"station-poor-native.png"),ImageFormat.Png);rich.Save(Path.Combine(preview,"station-rich-native.png"),ImageFormat.Png);mega.Save(Path.Combine(preview,"station-mega-native.png"),ImageFormat.Png);
   }
  }
 }
}
'@
[AlmanacArtCompiler]::Compile($source,$preview,$header)
Write-Output "Compiled $header"
