param()
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$root=Split-Path $PSScriptRoot
# Asset compilation only: preserve sources, fit the scene to native dimensions,
# quantize to a shared 32-colour palette and embed byte indices (no runtime PNG).
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;
using System.Drawing;
using System.IO;
using System.Text;
public static class LaveBake {
 static readonly string[] Hex={"080d18","101b29","192c3c","263d50","355366","527080","78909a","a9b1aa","263337","3b4946","566050","74765c","939471","b9ae83","dfcea1","fff0c4","362b26","523c2c","705037","916b43","b38b53","d4a65e","f2bd67","ffe39b","512f27","784334","a55f41","ce8550","145567","21818b","55bec2","a0eeee"};
 public static void Atlas(string root,string name,int cols,int rows,int cw,int ch) {
  var pal=new Color[Hex.Length];for(int i=0;i<pal.Length;i++)pal[i]=ColorTranslator.FromHtml("#"+Hex[i]);
  using(var src=new Bitmap(Path.Combine(root,"assets/source/lave-station",name+".png")))
  using(var preview=new Bitmap(cols*cw,rows*ch)){
   var h=new StringBuilder("/* Compiled transparent sprite atlas. Index 255 = transparent. */\nstatic const unsigned char lave_"+name+"_pixels["+cols*rows+"]["+cw*ch+"]={\n");
   for(int cell=0;cell<cols*rows;cell++){
    int x0=cell%cols*src.Width/cols,y0=cell/cols*src.Height/rows,x1=(cell%cols+1)*src.Width/cols,y1=(cell/cols+1)*src.Height/rows;
    int bx=x1,by=y1,ex=x0,ey=y0;
    for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)if(src.GetPixel(x,y).A>128){bx=Math.Min(bx,x);by=Math.Min(by,y);ex=Math.Max(ex,x);ey=Math.Max(ey,y);}
    if(ex<bx||ey<by)throw new Exception("Empty atlas cell "+name+" "+cell);
    double scale=Math.Min((cw-2.0)/(ex-bx+1),(ch-2.0)/(ey-by+1));int dw=Math.Max(1,(int)Math.Round((ex-bx+1)*scale)),dh=Math.Max(1,(int)Math.Round((ey-by+1)*scale));
    int ox=(cw-dw)/2,oy=ch-1-dh;h.Append("{\n");
    for(int y=0;y<ch;y++)for(int x=0;x<cw;x++){
     int best=255;
     if(x>=ox&&x<ox+dw&&y>=oy&&y<oy+dh){
      int sx=bx+Math.Min(ex-bx,(int)((x-ox+.5)*(ex-bx+1)/dw)),sy=by+Math.Min(ey-by,(int)((y-oy+.5)*(ey-by+1)/dh));
      var c=src.GetPixel(sx,sy);if(c.A>128){int dist=int.MaxValue;for(int i=0;i<pal.Length;i++){int dr=c.R-pal[i].R,dg=c.G-pal[i].G,db=c.B-pal[i].B;int d=2*dr*dr+3*dg*dg+db*db;if(d<dist){dist=d;best=i;}}}
     }
     if(best!=255)preview.SetPixel(cell%cols*cw+x,cell/cols*ch+y,pal[best]);h.Append(best+",");if(x==cw-1)h.Append('\n');
    }h.Append("},\n");
   }
   h.Append("};\n");File.WriteAllText(Path.Combine(root,"src/generated/lave-"+name+"-pixels.h"),h.ToString(),new UTF8Encoding(false));
   preview.Save(Path.Combine(root,"assets/generated/lave-station",name+".png"),System.Drawing.Imaging.ImageFormat.Png);
  }
 }
 public static void Run(string root) {
  var pal=new Color[Hex.Length]; for(int i=0;i<pal.Length;i++)pal[i]=ColorTranslator.FromHtml("#"+Hex[i]);
  string[] names={"arrivals","shop","canteen","cargo","guild","clinic","customs"};
  var h=new StringBuilder("/* Generated by tools/bake-lave-station.ps1. 7 x 340 x 168, 32-colour byte indices. */\n");
  h.Append("static const unsigned lave_room_palette[32]={\n");
  foreach(var c in pal)h.AppendFormat("RGB({0},{1},{2}),",c.R,c.G,c.B);h.Append("\n};\n");
  Directory.CreateDirectory(Path.Combine(root,"assets/generated/lave-station"));
  h.Append("static const unsigned char lave_room_pixels[7][57120]={\n");
  foreach(string name in names)using(var src=new Bitmap(Path.Combine(root,"assets/source/lave-station",name+".png")))using(var dst=new Bitmap(340,168)) {
   h.Append("{ /* "+name+" */\n");
   for(int y=0;y<168;y++)for(int x=0;x<340;x++) {
    int r=0,g=0,b=0,n=0;
    for(int yy=y*src.Height/168;yy<(y+1)*src.Height/168;yy++)for(int xx=x*src.Width/340;xx<(x+1)*src.Width/340;xx++){var c=src.GetPixel(xx,yy);r+=c.R;g+=c.G;b+=c.B;n++;}
    r/=n;g/=n;b/=n;int best=0,dist=int.MaxValue;
    for(int i=0;i<pal.Length;i++){int dr=r-pal[i].R,dg=g-pal[i].G,db=b-pal[i].B;int d=2*dr*dr+3*dg*dg+db*db;if(d<dist){dist=d;best=i;}}
    dst.SetPixel(x,y,pal[best]);h.Append(best+",");if((y*340+x)%40==39)h.Append('\n');
   }
   h.Append("},\n"); dst.Save(Path.Combine(root,"assets/generated/lave-station",name+".png"),System.Drawing.Imaging.ImageFormat.Png);
  }
  string heroPath=Path.Combine(root,"assets/source/lave-station","lave-arrivals-hero.png");
  if(File.Exists(heroPath))using(var src=new Bitmap(heroPath))using(var dst=new Bitmap(340,168)) {
   h.Append("};\nstatic const unsigned char lave_arrivals_hero_pixels[57120]={\n");
   for(int y=0;y<168;y++)for(int x=0;x<340;x++) {
    int r=0,g=0,b=0,n=0;
    for(int yy=y*src.Height/168;yy<(y+1)*src.Height/168;yy++)for(int xx=x*src.Width/340;xx<(x+1)*src.Width/340;xx++){var c=src.GetPixel(xx,yy);r+=c.R;g+=c.G;b+=c.B;n++;}
    r/=n;g/=n;b/=n;int best=0,dist=int.MaxValue;
    for(int i=0;i<pal.Length;i++){int dr=r-pal[i].R,dg=g-pal[i].G,db=b-pal[i].B;int d=2*dr*dr+3*dg*dg+db*db;if(d<dist){dist=d;best=i;}}
    dst.SetPixel(x,y,pal[best]);h.Append(best+",");if((y*340+x)%40==39)h.Append('\n');
   }
   h.Append("};\n");dst.Save(Path.Combine(root,"assets/generated/lave-station","lave-arrivals-hero.png"),System.Drawing.Imaging.ImageFormat.Png);
  } else h.Append("};\n");
  File.WriteAllText(Path.Combine(root,"src/generated/lave-room-pixels.h"),h.ToString(),new UTF8Encoding(false));
 }
}
'@
[LaveBake]::Run($root)
if(Test-Path "$root/assets/source/lave-station/props.png"){[LaveBake]::Atlas($root,'props',4,2,32,32)}
if(Test-Path "$root/assets/source/lave-station/crew.png"){[LaveBake]::Atlas($root,'crew',8,1,32,64)}
Write-Output 'Compiled seven native 340x168 room plates: 399840 bytes plus 128-byte palette.'
