"""Convert the approved 1665x944 broadcast art to the PSP's 480x272 grid.

This is asset compilation, not a replacement illustration: retain the exact
composition, presenter, studio, window and channel ident from the supplied art.
UI labels/captions are drawn by the engine. No PNG decode or heap use at runtime.
"""
from pathlib import Path
from PIL import Image
import hashlib
import json

root = Path(__file__).resolve().parents[1]
src = root / 'assets/source/local-tv-reference.png'
im = Image.open(src).convert('RGB').resize((480, 272), Image.Resampling.LANCZOS)
preview = root / 'assets/preview/local-tv'
preview.mkdir(parents=True, exist_ok=True)
values = [(0x8000 | ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3))
          for r, g, b in im.getdata()]
quantized = Image.new('RGB', im.size)
quantized.putdata([tuple(((v >> shift) & 31) * 255 // 31 for shift in (10, 5, 0)) for v in values])
quantized.save(preview / 'reference-native.png')
out = root / 'src/local-tv-art.h'
lines = ['/* Approved reference: 480x272 ARGB1555; generated by tools/bake-local-tv.py. */',
         '#include <stdint.h>', 'static const uint16_t local_tv_art[480*272] = {']
for i in range(0, len(values), 24):
    lines.append(' ' + ','.join(f'0x{v:04x}' for v in values[i:i+24]) + ',')
lines.append('};\n')
out.write_text('\n'.join(lines), encoding='ascii')
(preview / 'provenance.json').write_text(json.dumps({
    'source': 'User-supplied approved Lave Local TV concept',
    'source_sha256': hashlib.sha256(src.read_bytes()).hexdigest(),
    'conversion': 'Lanczos downsample to 480x272, RGB 5-bit quantization; opaque ARGB1555',
    'bytes': 480*272*2,
    'runtime': 'Original artwork; native UI overlay; bounded window and mouth animation'
}, indent=2))
print(f'Compiled {out}: {len(values)*2:,} bytes of art')
