param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$chartSource=Join-Path $ProjectRoot 'assets/source/deep-chart/nebula.png'
$chartPreview=Join-Path $ProjectRoot 'assets/preview/deep-chart'
New-Item -ItemType Directory -Force -Path $chartPreview | Out-Null
$chartReferences=@([System.Drawing.Bitmap].Assembly.Location,[System.Drawing.Rectangle].Assembly.Location) | Select-Object -Unique
Add-Type -ReferencedAssemblies $chartReferences -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
public static class DeepChartBaker {
 public static void Bake(string source,string preview,string header){
  using(Bitmap original=new Bitmap(source))
  using(Bitmap image=new Bitmap(512,256,PixelFormat.Format32bppArgb)){
   using(Graphics g=Graphics.FromImage(image)){
    g.InterpolationMode=InterpolationMode.HighQualityBicubic;
    g.PixelOffsetMode=PixelOffsetMode.HighQuality;
    g.DrawImage(original,new Rectangle(0,0,512,256));
   }
   using(StreamWriter w=new StreamWriter(header,false)){
    w.NewLine="\n";
    w.WriteLine("/* Generated by tools/bake-deep-chart.ps1. Starless, authored galaxy light. */");
    w.WriteLine("static const unsigned short chart_nebula[256][512]={");
    for(int y=0;y<256;y++){
     w.Write("{");
     for(int x=0;x<512;x++){
      Color c=image.GetPixel(x,y);
      // Match the surrounding dark navy and leave headroom for real stars.
      double edge=Math.Min(1.0,Math.Min(Math.Min(x,511-x),Math.Min(y,255-y))/14.0);
      int r=2+(int)(c.R*.40*edge),g=5+(int)(c.G*.48*edge),b=11+(int)(c.B*.58*edge);
      int packed=((r>>3)<<11)|((g>>2)<<5)|(b>>3);
      w.Write("0x"+packed.ToString("X4")+",");
      if((x&15)==15)w.WriteLine();
      image.SetPixel(x,y,Color.FromArgb(255,r,g,b));
     }
     w.WriteLine("},");
    }
    w.WriteLine("};");
   }
   image.Save(Path.Combine(preview,"nebula-native.png"),ImageFormat.Png);
  }
 }
}
'@
[DeepChartBaker]::Bake($chartSource,$chartPreview,(Join-Path $ProjectRoot 'src/generated/deep-chart-nebula.h'))
Write-Output 'Baked 512x256 RGB565 galaxy texture (256 KiB, embedded in EBOOT).'
