param()
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$root=Split-Path $PSScriptRoot
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;
using System.Drawing;
using System.IO;
using System.Text;
public static class LaveLandscapeBake {
 static readonly string[] Hex={"07140f","102319","1a3820","25502a","326b32","43863a","5d9f42","7bb54a","a5ca56","d5dc70","312820","483526","66472f","805936","a17547","c69255","e1b976","162e2c","26504a","367766","649382","9ca58b","c2c5a3","e0dfbd","56616a","76818b","a1a8aa","d3d1bc","bd7b38","e8a838","ffd663","eaf2d0"};
 static Color[] Palette(){var p=new Color[Hex.Length];for(int i=0;i<p.Length;i++)p[i]=ColorTranslator.FromHtml("#"+Hex[i]);return p;}
 public static void Run(string root){
  var pal=Palette();Directory.CreateDirectory(Path.Combine(root,"assets/generated/lave-landscape"));
  using(var src=new Bitmap(Path.Combine(root,"assets/source/lave-landscape/vegetation-atlas.png")))
  using(var preview=new Bitmap(192,128)){
   var h=new StringBuilder("/* Generated by tools/bake-lave-landscape.ps1; 8 transparent 48x64 Lave I pixel sprites. */\nstatic const unsigned lave_vegetation_palette[32]={\n");
   foreach(var c in pal)h.AppendFormat("RGB({0},{1},{2}),",c.R,c.G,c.B);h.Append("\n};\nstatic const unsigned char lave_vegetation_pixels[8][3072]={\n");
   for(int cell=0;cell<8;cell++){
    int x0=cell%4*src.Width/4,y0=cell<4?80:640,x1=(cell%4+1)*src.Width/4,y1=cell<4?640:src.Height,bx=x1,by=y1,ex=x0,ey=y0;
    for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)if(src.GetPixel(x,y).A>160){bx=Math.Min(bx,x);by=Math.Min(by,y);ex=Math.Max(ex,x);ey=Math.Max(ey,y);}
    if(ex<bx||ey<by)throw new Exception("Empty vegetation cell "+cell);
    double scale=Math.Min(46.0/(ex-bx+1),63.0/(ey-by+1));int dw=Math.Max(1,(int)Math.Round((ex-bx+1)*scale)),dh=Math.Max(1,(int)Math.Round((ey-by+1)*scale));int ox=(48-dw)/2,oy=64-dh;
    h.Append("{\n");
    for(int y=0;y<64;y++)for(int x=0;x<48;x++){
     int index=255;
     if(x>=ox&&x<ox+dw&&y>=oy&&y<oy+dh){int sx=bx+Math.Min(ex-bx,(int)((x-ox+.5)*(ex-bx+1)/dw)),sy=by+Math.Min(ey-by,(int)((y-oy+.5)*(ey-by+1)/dh));var c=src.GetPixel(sx,sy);if(c.A>160){int best=0,dist=int.MaxValue;for(int i=0;i<pal.Length;i++){int dr=c.R-pal[i].R,dg=c.G-pal[i].G,db=c.B-pal[i].B,d=2*dr*dr+3*dg*dg+db*db;if(d<dist){dist=d;best=i;}}index=best;preview.SetPixel(cell%4*48+x,cell/4*64+y,pal[index]);}}
     h.Append(index).Append(',');if(x==47)h.Append('\n');
    }h.Append("},\n");
   }
   h.Append("};\n");File.WriteAllText(Path.Combine(root,"src/generated/lave-landscape-pixels.h"),h.ToString(),new UTF8Encoding(false));preview.Save(Path.Combine(root,"assets/generated/lave-landscape/vegetation-atlas.png"),System.Drawing.Imaging.ImageFormat.Png);
  }
 }
}
'@
[LaveLandscapeBake]::Run($root)
Write-Output 'Compiled the eight-cell Lave I vegetation atlas to compact 32-colour PSP sprites.'
