"""Bake AI pixel-art PNGs into chroma-keyed C arrays."""
from PIL import Image
from pathlib import Path

ASSETS = Path(r"C:\Users\skarm\.cursor\projects\c-Users-skarm-Documents-Codex-2026-09-14-let\assets")
OUT = Path(r"C:\Users\skarm\Documents\Codex\2026-09-14\let\outputs\arcelite-psp\src\sprites.h")

JOBS = [
    ("pad", "psp-3000-pixel.png", 212, 118),
    ("planet", "icon-planet.png", 32, 32),
    ("ship", "icon-ship.png", 32, 32),
    ("system", "icon-system.png", 32, 32),
    ("station", "icon-station.png", 32, 32),
    ("holo", "holo-ship.png", 84, 36),
    ("radar", "holo-radar.png", 70, 70),
]

def magenta(p):
    r, g, b = p[:3]
    return r > 140 and b > 120 and g < 130 and (r + b) > (g * 3 + 40)

def mark_background(im):
    """Only punch out magenta connected to the image border so face buttons stay."""
    pix = im.load()
    w, h = im.size
    seen = bytearray(w * h)
    stack = []
    for x in range(w):
        stack.append((x, 0))
        stack.append((x, h - 1))
    for y in range(h):
        stack.append((0, y))
        stack.append((w - 1, y))
    while stack:
        x, y = stack.pop()
        if x < 0 or y < 0 or x >= w or y >= h:
            continue
        i = y * w + x
        if seen[i]:
            continue
        seen[i] = 1
        if not magenta(pix[x, y]):
            continue
        pix[x, y] = (255, 0, 255, 0)
        stack.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))

def convert(path, max_w, max_h):
    im = Image.open(path).convert("RGBA")
    mark_background(im)
    pix = im.load()
    w, h = im.size
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            r, g, b, a = pix[x, y]
            if a >= 16 and not magenta((r, g, b)):
                xs.append(x)
                ys.append(y)
    im = im.crop((min(xs), min(ys), max(xs) + 1, max(ys) + 1))
    scale = min(max_w / im.width, max_h / im.height)
    nw = max(8, int(round(im.width * scale)))
    nh = max(8, int(round(im.height * scale)))
    im = im.resize((nw, nh), Image.NEAREST)
    mark_background(im)
    pix = im.load()
    data = []
    for y in range(nh):
        for x in range(nw):
            r, g, b, a = pix[x, y]
            if magenta((r, g, b)) or a < 16:
                data.append(0)
            else:
                data.append(r | (g << 8) | (b << 16) | 0xFF000000)
    return nw, nh, data

lines = [
    "/* Baked 16-bit AI sprites. Magenta chroma is 0. Regenerated by tools/bake-sprites.py */",
    "static void blit_spr(int x,int y,int w,int h,const unsigned *p){for(int j=0;j<h;j++)for(int i=0;i<w;i++){unsigned c=p[j*w+i];if(c)pixel(x+i,y+j,c);}}",
    "static void blit_spr_fit(int x,int y,int w,int h,const unsigned *p,int dw,int dh){if(dw<1)dw=1;if(dh<1)dh=1;for(int j=0;j<dh;j++)for(int i=0;i<dw;i++){unsigned c=p[(j*h/dh)*w+(i*w/dw)];if(c)pixel(x+i,y+j,c);}}",
]
for name, filename, mw, mh in JOBS:
    w, h, data = convert(ASSETS / filename, mw, mh)
    lines.append(f"enum {{ SPR_{name.upper()}_W={w}, SPR_{name.upper()}_H={h} }};")
    lines.append(f"static const unsigned spr_{name}[]={{")
    row = []
    for i, value in enumerate(data):
        row.append(f"0x{value:08X}u" if value else "0")
        if len(row) == 10:
            lines.append(" " + ",".join(row) + ",")
            row = []
    if row:
        lines.append(" " + ",".join(row))
    lines.append("};")
    print(f"{name}: {w}x{h}")
OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
print("wrote", OUT, "bytes", OUT.stat().st_size)
