param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$sourcePath = Join-Path $ProjectRoot 'assets/source/local-tv-mira.png'
$headerPath = Join-Path $ProjectRoot 'src/local-tv-mira.h'
$source = [System.Drawing.Bitmap]::new($sourcePath)
try {
    $left=$source.Width; $top=$source.Height; $right=-1; $bottom=-1
    for($y=0;$y -lt $source.Height;$y++) { for($x=0;$x -lt $source.Width;$x++) {
        if($source.GetPixel($x,$y).A -ge 128) { if($x -lt $left){$left=$x}; if($x -gt $right){$right=$x}; if($y -lt $top){$top=$y}; if($y -gt $bottom){$bottom=$y} }
    } }
    if($right -lt $left){ throw 'Mira sprite has no opaque pixels' }
    $crop = [System.Drawing.Rectangle]::FromLTRB($left,$top,$right+1,$bottom+1)
    $scale = [Math]::Min(96.0/$crop.Width,128.0/$crop.Height)
    $dw=[Math]::Max(1,[int][Math]::Floor($crop.Width*$scale));$dh=[Math]::Max(1,[int][Math]::Floor($crop.Height*$scale))
    $canvas=[System.Drawing.Bitmap]::new(96,128,[System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $graphics=[System.Drawing.Graphics]::FromImage($canvas)
    try {
        $graphics.Clear([System.Drawing.Color]::Transparent)
        $graphics.InterpolationMode=[System.Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
        $graphics.PixelOffsetMode=[System.Drawing.Drawing2D.PixelOffsetMode]::Half
        $graphics.DrawImage($source,[System.Drawing.Rectangle]::new((96-$dw)/2,(128-$dh)/2,$dw,$dh),$crop,[System.Drawing.GraphicsUnit]::Pixel)
    } finally { $graphics.Dispose() }
    $lines=[System.Collections.Generic.List[string]]::new()
    $lines.Add('/* Generated by tools/bake-local-tv-mira.ps1; ARGB1555 with alpha bit. */')
    $lines.Add('#include <stdint.h>');$lines.Add('#define LOCAL_TV_MIRA_W 96');$lines.Add('#define LOCAL_TV_MIRA_H 128')
    $lines.Add('static const uint16_t local_tv_mira[LOCAL_TV_MIRA_W*LOCAL_TV_MIRA_H] = {')
    $row=[System.Collections.Generic.List[string]]::new()
    for($y=0;$y -lt 128;$y++) { for($x=0;$x -lt 96;$x++) {
        $c=$canvas.GetPixel($x,$y);$v=0;if($c.A -ge 128){$r5=[int]$c.R -shr 3;$g5=[int]$c.G -shr 3;$b5=[int]$c.B -shr 3;$v=0x8000 -bor ($r5 -shl 10) -bor ($g5 -shl 5) -bor $b5};$row.Add(('0x{0:X4}' -f $v))
        if($row.Count -eq 16){$lines.Add('  '+($row -join ',')+',');$row.Clear()}
    } }
    if($row.Count){$lines.Add('  '+($row -join ',')+',')};$lines.Add('};');$lines.Add('')
    [IO.File]::WriteAllLines($headerPath,$lines,[Text.Encoding]::ASCII)
    Write-Output "Baked $headerPath ($dw`x$dh source fit into 96x128)"
} finally { $source.Dispose(); if($canvas){$canvas.Dispose()} }
