"""Flood-key leftover magenta in baked sprite arrays."""
import re
from pathlib import Path

path = Path(r"C:\Users\skarm\Documents\Codex\2026-09-14\let\outputs\arcelite-psp\src\sprites.h")
text = path.read_text(encoding="ascii")

def is_pink(v):
    if v == 0:
        return True
    r, g, b = v & 255, (v >> 8) & 255, (v >> 16) & 255
    return r > 130 and b > 70 and g < 120 and r > g + 25 and (r + b) > g * 2 + 40

def clean(w, h, data):
    pix = data[:]
    from collections import deque
    q = deque()
    seen = [False] * (w * h)

    def try_add(x, y):
        if 0 <= x < w and 0 <= y < h and not seen[y * w + x] and is_pink(pix[y * w + x]):
            seen[y * w + x] = True
            q.append((x, y))

    for x in range(w):
        try_add(x, 0)
        try_add(x, h - 1)
    for y in range(h):
        try_add(0, y)
        try_add(w - 1, y)
    while q:
        x, y = q.popleft()
        pix[y * w + x] = 0
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
            try_add(x + dx, y + dy)
    extra = pix[:]
    for y in range(h):
        for x in range(w):
            if pix[y * w + x] == 0:
                continue
            edge = False
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h and pix[ny * w + nx] == 0:
                    edge = True
                    break
            if edge and is_pink(pix[y * w + x]):
                extra[y * w + x] = 0
    return extra

def emit(name, w, h, data):
    lines = [f"enum {{ SPR_{name.upper()}_W={w}, SPR_{name.upper()}_H={h} }};", f"static const unsigned spr_{name}[]={{"]
    row = []
    for value in data:
        row.append(f"0x{value:08X}u" if value else "0")
        if len(row) == 10:
            lines.append(" " + ",".join(row) + ",")
            row = []
    if row:
        lines.append(" " + ",".join(row))
    lines.append("};")
    return "\n".join(lines)

header = "/* Baked 16-bit AI sprites. Magenta chroma is 0. Regenerated by tools/bake-sprites.py */\nstatic void blit_spr(int x,int y,int w,int h,const unsigned *p){for(int j=0;j<h;j++)for(int i=0;i<w;i++){unsigned c=p[j*w+i];if(c)pixel(x+i,y+j,c);}}\nstatic void blit_spr_fit(int x,int y,int w,int h,const unsigned *p,int dw,int dh){for(int j=0;j<dh;j++)for(int i=0;i<dw;i++){unsigned c=p[(j*h/dh)*w+(i*w/dw)];if(c)pixel(x+i,y+j,c);}}\n"
parts = [header]
for name in ("pad", "planet", "ship", "system", "station"):
    w = int(re.search(rf"SPR_{name.upper()}_W=(\d+)", text).group(1))
    h = int(re.search(rf"SPR_{name.upper()}_H=(\d+)", text).group(1))
    body = re.search(rf"static const unsigned spr_{name}\[\]=\{{(.*?)\}};", text, re.S).group(1)
    values = [int(v[2:-1], 16) if v.startswith("0x") else 0 for v in re.findall(r"0x[0-9A-Fa-f]+u|\b0\b", body)]
    if len(values) != w * h:
        raise SystemExit(f"{name}: expected {w*h} got {len(values)}")
    cleaned = clean(w, h, values)
    kept = sum(1 for v in cleaned if v)
    print(f"{name}: {w}x{h} opaque {kept}/{w*h}")
    parts.append(emit(name, w, h, cleaned))
path.write_text("\n".join(parts) + "\n", encoding="ascii")
print("rewrote", path)
