// Read Elite-A's documented blueprint macros and convert the geometry to C.
// Original data: Angus Duggan / Acornsoft; annotations: Mark Moxon.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const dir=path.join(root,'elite-a/1-source-files/main-sources');
const ships=new Map();
for(const file of fs.readdirSync(dir).filter(x=>/^elite-ships-[a-z]\.asm$/.test(x)).sort()) {
  let name='',kind='';
  for(const line of fs.readFileSync(path.join(dir,file),'utf8').split(/\r?\n/)) {
    const label=line.match(/^\.SHIP_(\w+?)_(VERTICES|EDGES|FACES)\s*$/);
    if(label){name=label[1];kind=label[2];if(!ships.has(name))ships.set(name,{name,file,VERTICES:[],EDGES:[],FACES:[]});continue;}
    if(/^\./.test(line)){kind='';continue;}
    const macro=line.match(/^\s+(VERTEX|EDGE|FACE)\s+([^\\]+)/);
    if(!macro||!kind)continue;
    const s=ships.get(name), nums=macro[2].split(',').map(x=>Number(x.trim()));
    if(nums.some(x=>!Number.isFinite(x)))throw Error('Non-numeric geometry '+file+': '+line);
    // Repeated definitions across blueprint banks must not duplicate geometry.
    if(s.file===file)s[kind].push(nums);
  }
}
const output=['/* Generated by tools/extract-ships.mjs. Do not hand edit. */','#include "mesh.h"'];
const manifest=[];let index=0;
for(const s of ships.values()) {
  const vertices=s.VERTICES.map(v=>v.slice(0,3));if(!vertices.length)continue;
  const triangles=[];
  s.FACES.forEach((normal,face)=>{
    const ids=[...new Set(s.EDGES.filter(e=>e[2]!==e[3]&&(e[2]===face||e[3]===face)).flatMap(e=>e.slice(0,2)))];
    if(ids.length<3)return;
    if(ids.some(i=>i<0||i>=vertices.length))throw Error('Bad vertex '+s.name);
    const center=[0,1,2].map(k=>ids.reduce((sum,i)=>sum+vertices[i][k],0)/ids.length);
    let n=normal.slice(0,3),len=Math.hypot(...n);if(!len)return;n=n.map(x=>x/len);
    let u=vertices[ids[0]].map((x,k)=>x-center[k]);len=Math.hypot(...u);if(!len)return;u=u.map(x=>x/len);
    const v=[n[1]*u[2]-n[2]*u[1],n[2]*u[0]-n[0]*u[2],n[0]*u[1]-n[1]*u[0]];
    const angle=i=>{const d=vertices[i].map((x,k)=>x-center[k]);return Math.atan2(d.reduce((a,x,k)=>a+x*v[k],0),d.reduce((a,x,k)=>a+x*u[k],0));};
    ids.sort((a,b)=>angle(a)-angle(b));
    for(let k=1;k<ids.length-1;k++)triangles.push([ids[0],ids[k],ids[k+1],...n]);
  });
  if(!triangles.length)continue;
  output.push(`static const Vec3 v${index}[] = {${vertices.map(v=>'{'+v.join(',')+'}').join(',')}};`);
  output.push(`static const MeshTri t${index}[] = {${triangles.map(t=>'{'+t.slice(0,3).join(',')+',{'+t.slice(3).map(x=>x.toFixed(6)+'f').join(',')+'}}').join(',')}};`);
  manifest.push({name:s.name,index,vertices:vertices.length,triangles:triangles.length,source:s.file});index++;
}
output.push('const Mesh meshes[] = {');
for(const s of manifest)output.push(`{"${s.name.replaceAll('_',' ')}", ${s.vertices}, ${s.triangles}, v${s.index}, t${s.index}},`);
output.push('};',`const int mesh_count=${manifest.length};`);
fs.mkdirSync(path.join(root,'src'),{recursive:true});
fs.writeFileSync(path.join(root,'src/ships.c'),output.join('\n'));
fs.writeFileSync(path.join(root,'tools/ships-manifest.json'),JSON.stringify(manifest,null,2));
console.log(`Converted ${manifest.length} Elite-A ship blueprints (${manifest.reduce((a,s)=>a+s.triangles,0)} triangles).`);
