{
 TEST_INIT();commander_active_slot=0;change_page(STATUS);
 {unsigned a=portrait_seeded(77,TRADERS,-1),b=portrait_seeded(77,TRADERS,-1),c=portrait_seeded(78,TRADERS,-1);INPUT_CHECK(a==b&&a!=c,"portraits: identity seed is deterministic and varied");INPUT_CHECK(portrait_valid(a)&&portrait_version(a)==PORTRAIT_DNA_VERSION,"portraits: DNA is self-versioned for future extensions");INPUT_CHECK(a==portrait_seeded(77,LAW,-1)&&a==portrait_seeded(77,PIRATES,-1),"portraits: faction changes uniform without replacing identity");unsigned computer=portrait_ship_computer();INPUT_CHECK(portrait_species(computer)==PORTRAIT_ROBOT,"portraits: ship computer has a persistent robot identity");int all_species=1,all_bases=1;for(int s=0;s<PORTRAIT_SPECIES_COUNT;s++){unsigned sample=portrait_seeded(1,EXPLORERS,s);all_species&=portrait_species(sample)==s;int base=portrait_pulp_base(sample);all_bases&=base>=0&&base<PORTRAIT_PULP_BASE_COUNT;}INPUT_CHECK(all_species,"portraits: all ten playable and NPC species can be assembled");INPUT_CHECK(all_bases&&PORTRAIT_PULP_BASE_COUNT==96,"portraits: all 96 authored pulp bases are available");}
 row=2;input(PSP_CTRL_CROSS,0,.016f,0,0);snprintf(profile_draft,25,"NOVA REED");input(PSP_CTRL_START,0,.016f,0,0);
 INPUT_CHECK(!strcmp(game.commander_name,"NOVA REED")&&!profile_mode,"profile: controller name editor applies commander name");
 row=2;input(PSP_CTRL_CROSS,0,.016f,0,0);profile_draft[0]=0;input(PSP_CTRL_START,0,.016f,0,0);
 INPUT_CHECK(profile_mode&&!strcmp(game.commander_name,"NOVA REED"),"profile: blank names cannot replace identity");input(PSP_CTRL_CIRCLE,0,.016f,0,0);
 row=3;game.commander_portrait=3;input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(profile_portrait_edit&&(game.commander_portrait&PORTRAIT_DNA_MARK),"profile: legacy portrait opens in modular creator");input(PSP_CTRL_RIGHT,0,.016f,0,0);INPUT_CHECK(portrait_species(game.commander_portrait)==PORTRAIT_ELONGATED,"profile: creator can change commander species");input(PSP_CTRL_CIRCLE,0,.016f,0,0);unsigned chosen_portrait=game.commander_portrait;
 game.credits=2345;game.bounty_claimed[7]=3;row=0;input(PSP_CTRL_CROSS,0,.016f,0,0);if(profile_confirm)input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(profile_info[0].state==1&&!strcmp(profile_info[0].name,"NOVA REED"),"profile: slot one stores named commander");
 game.credits=7890;snprintf(game.commander_name,25,"ORION VALE");profile_slot=1;input(PSP_CTRL_CROSS,0,.016f,0,0);if(profile_confirm)input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(profile_info[0].credits==2345&&profile_info[1].credits==7890,"profile: three-slot files remain independent");
 profile_slot=2;game.credits=5678;snprintf(game.commander_name,25,"LYRA SOL");profile_save();INPUT_CHECK(profile_info[2].credits==5678&&profile_info[1].credits==7890&&profile_info[0].credits==2345,"profile: third save slot stores independent stats");profile_delete();profile_slot=1;
 game.credits=9000;input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(profile_confirm==1,"profile: replacing a slot needs confirmation");input(PSP_CTRL_CIRCLE,0,.016f,0,0);profile_refresh();INPUT_CHECK(profile_info[1].credits==7890,"profile: cancelling overwrite preserves saved progress");
 change_page(INTRO);intro_choice=2;input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(page==STATUS&&profile_from_intro,"profile: main-menu load opens three save cards");profile_slot=0;input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(profile_confirm==2,"profile: loading confirms loss of unsaved progress");input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==HOME&&game.credits==2345&&game.commander_portrait==chosen_portrait&&!strcmp(game.commander_name,"NOVA REED")&&game.bounty_claimed[7]==3&&!game.npc[BOUNTY_NPC_FIRST].alive,"profile: load restores modular identity, money and completed bounty targets");
 change_page(STATUS);row=0;input(PSP_CTRL_CROSS,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);FILE *bad=fopen("commander.sav","wb");if(bad){fputs("damaged",bad);fclose(bad);}profile_refresh();INPUT_CHECK(profile_info[0].state==3,"profile: damaged save card advertises recovery backup");
 profile_open_load();profile_slot=1;input(PSP_CTRL_SQUARE,0,.016f,0,0);INPUT_CHECK(profile_confirm==3,"profile: delete is always confirmed");input(PSP_CTRL_CIRCLE,0,.016f,0,0);INPUT_CHECK(profile_file_exists("commander-2.sav"),"profile: cancelling delete keeps save");input(PSP_CTRL_SQUARE,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(!profile_file_exists("commander-2.sav")&&profile_info[0].state==3,"profile: deleting a slot leaves other slots intact");
 profile_slot=0;profile_delete();commander_active_slot=0;profile_from_intro=profile_confirm=profile_mode=0;TEST_INIT();
}
