{
 TEST_INIT();launch(&game);page=FLIGHT;game.voice_time=0;game.message_time=0;
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==FLIGHT,"comms: Triangle press waits before choosing tap or hold");
 for(int i=0;i<12;i++)input(0,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==COMMS_PANEL,"comms: holding Triangle opens channel control without hailing");
 row=0;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(quiet_comms==1,"comms: quiet mode toggles from channel control");
 game.message_time=0;speak(&game,VOICE_KEI,"A quiet test.");
 INPUT_CHECK(!speech_active(),"comms: muted chatter is not an invisible confirmation blocker");
 input(PSP_CTRL_CIRCLE,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!radio_dirty,"comms: close saves preferences and restores flight");
 quiet_comms=0;radio_dirty=0;remove("radio.cfg");remove("radio.cfg.bak");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Incoming channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);input(0,0,.05f,0,0);
 INPUT_CHECK(page==FLIGHT&&comms_quick&&game.encounter_kind==ENCOUNTER_PIRATE,"comms: a Triangle tap opens the Talk/Ignore choice");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Quick channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);for(int i=0;i<12;i++)input(0,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==FLIGHT&&comms_quick,"comms: holding Triangle opens the quick respond/ignore overlay over flight");input(0,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==COMMS_PANEL&&comms_encounter_conversation,"comms: X confirms the highlighted Respond choice after Triangle is released");row=2;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT,"comms: ending the full discussion returns to flight");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Optional channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);input(0,0,.05f,0,0);input(PSP_CTRL_LEFT,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!comms_quick&&game.encounter_kind==ENCOUNTER_NONE,"comms: Left then X confirms Ignore without another Triangle press");
 TEST_INIT();change_page(GALNET);galnet_tab=3;row=1;unsigned before=spacebook_likes[game.system];input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(spacebook_likes[game.system]==(before^2u),"spacebook: X reacts to the focused local post");
 input(PSP_CTRL_TRIANGLE,0,.016f,0,0);INPUT_CHECK(spacebook_comments,"spacebook: replies expand inside the feed");spacebook_comments=0;
 TEST_INIT();change_page(INTRO);intro_choice=2;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==CAMPAIGN&&!tutorial_active(&game),"intro: New game opens Open Channel without tutorial gates");
 TEST_INIT();change_page(INTRO);intro_choice=0;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==HOME&&tutorial_active(&game)&&game.tutorial_step==1,"intro: Start tutorial opens First Light");TEST_INIT();
}
