{
 TEST_INIT();launch(&game);page=FLIGHT;game.voice_time=0;game.message_time=0;
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==FLIGHT,"comms: Triangle press waits before choosing tap or hold");
 for(int i=0;i<12;i++)input(0,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==COMMS_PANEL,"comms: holding Triangle opens channel control without hailing");
 row=0;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT,"comms: first channel option dismisses and returns to flight");
 /* Exercise every channel action as well as the settings covered below/navigation tests. */
 TEST_INIT();launch(&game);change_page(COMMS_PANEL);row=1;selected_target=0;
 input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(page==COMMS_PANEL&&row==3&&!game.dock_stage,"comms: station Hail highlights REQUEST AUTO-DOCK without starting guidance");
 TEST_INIT();launch(&game);change_page(COMMS_PANEL);row=2;selected_target=2;autoaim=1;look_target=2;
 input(PSP_CTRL_CROSS,0,.016f,0,0);INPUT_CHECK(page==COMMS_PANEL&&!autoaim&&look_target==-1&&selected_target==0,"comms: Clear releases pursuit and restores hub reference");
 row=4;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==MISSIONLOG&&row==1&&tracked_mission==1,"comms: Guild opens the Guild entry in the mission log");
 TEST_INIT();change_page(COMMS_PANEL);row=5;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==WALK&&walk_kind==0,"comms: station walk opens the actual station while docked");
 TEST_INIT();launch(&game);change_page(COMMS_PANEL);row=5;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==COMMS_PANEL,"comms: station walk is refused in space");
 row=6;selected_target=0;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==COMMS_PANEL,"comms: salvage requires a real anomaly target");
 game.anomaly[0].alive=1;game.anomaly[0].pos=add(game.pos,(Vec3){0,0,100});selected_target=ANOMALY_ID_MIN;
 input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==WALK&&walk_kind==2&&walk_oxygen==100,"comms: nearby live anomaly opens tethered salvage with oxygen");
 TEST_INIT();change_page(COMMS_PANEL);row=6;game.anomaly[0].alive=1;
 game.anomaly[0].pos=game.pos;selected_target=ANOMALY_ID_MIN;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==COMMS_PANEL&&game.docked,"comms: salvage cannot bypass docking");
 TEST_INIT();launch(&game);page=FLIGHT;change_page(COMMS_PANEL);row=8;quiet_comms=0;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(quiet_comms==1,"comms: text chatter is controlled by the shared Comms panel");
 game.message_time=0;speak(&game,VOICE_KEI,"A quiet test.");
 INPUT_CHECK(!speech_active(),"comms: muted chatter is not an invisible confirmation blocker");
 change_page(COMMS_PANEL);row=0;
 input(PSP_CTRL_CIRCLE,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!radio_dirty,"comms: close saves preferences and restores flight");
 quiet_comms=0;radio_dirty=0;remove("radio.cfg");remove("radio.cfg.bak");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Incoming channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);input(0,0,.05f,0,0);
 INPUT_CHECK(page==FLIGHT&&comms_quick&&game.encounter_kind==ENCOUNTER_PIRATE,"comms: a Triangle tap opens the Talk/Ignore choice");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Quick channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);for(int i=0;i<12;i++)input(0,PSP_CTRL_TRIANGLE,.05f,0,0);
 INPUT_CHECK(page==FLIGHT&&comms_quick,"comms: holding Triangle opens the quick respond/ignore overlay over flight");input(0,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==COMMS_PANEL&&comms_encounter_conversation,"comms: X confirms the highlighted Respond choice after Triangle is released");row=2;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT,"comms: ending the full discussion returns to flight");
 TEST_INIT();launch(&game);page=FLIGHT;game.encounter_kind=ENCOUNTER_PIRATE;game.encounter=4;speak(&game,VOICE_CONTACT,"Optional channel.");
 input(PSP_CTRL_TRIANGLE,PSP_CTRL_TRIANGLE,.05f,0,0);input(0,0,.05f,0,0);input(PSP_CTRL_LEFT,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!comms_quick&&game.encounter_kind==ENCOUNTER_NONE,"comms: Left then X confirms Ignore without another Triangle press");
 TEST_INIT();change_page(GALNET);galnet_tab=3;row=0;social_emit(&game,SB_PAINT);unsigned before=game.social.post[0];input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(game.social.post[0]==(before^(1u<<30)),"spacebook: X reacts to the focused local post");
 input(PSP_CTRL_TRIANGLE,0,.016f,0,0);INPUT_CHECK(!spacebook_comments,"spacebook: Triangle does not open removed replies");spacebook_comments=0;
 TEST_INIT();change_page(INTRO);intro_profile_ready=1;profile_info[0].state=profile_info[1].state=profile_info[2].state=0;intro_choice=1;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==CAMPAIGN&&!tutorial_active(&game),"intro: New game opens Open Channel without tutorial gates");
 TEST_INIT();change_page(INTRO);intro_profile_ready=1;profile_info[0].state=profile_info[1].state=profile_info[2].state=0;intro_choice=3;input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==HOME&&tutorial_active(&game)&&game.tutorial_step==1,"intro: Start tutorial opens First Light");TEST_INIT();
}
