{
 TEST_INIT();station_tour_stage=STATION_TOUR_ROUTE;tracked_mission=0;page=CAMPAIGN;row=0;
 campaign_screen();INPUT_CHECK(strstr(dialogue_source,"Ryn Vale")!=0,"tracking: an available station tour cannot replace the selected story briefing");
 change_page(MISSIONLOG);row=1;input(PSP_CTRL_CROSS,0,.016f,0,0);input(PSP_CTRL_SELECT,0,.016f,0,0);
 campaign_screen();INPUT_CHECK(tracked_mission==1&&page==CAMPAIGN&&strstr(dialogue_source,"survey")!=0,"tracking: Guild selected in the log opens its own next-step conversation");
 input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!game.docked,"tracking: Guild Launch reply works without a separate Guild menu");
 input(0,0,.016f,0,0);
 INPUT_CHECK(station_tour_stage==STATION_TOUR_ROUTE&&game.route_goal!=STATION_TOUR_DEST,"tracking: untracked welcome tour cannot reroute a flight");
 change_page(MISSIONLOG);row=mission_log_count()-1;input(PSP_CTRL_SELECT,0,.016f,0,0);
 INPUT_CHECK(page==CAMPAIGN&&tracked_mission==TRACK_STATION_TOUR,"tracking: welcome tour is explicitly selectable in Mission Log");
 campaign_screen();INPUT_CHECK(strstr(dialogue_source,"Reorte Hub")!=0,"tracking: selected welcome mission shows its own briefing");
 change_page(MISSIONLOG);row=0;input(PSP_CTRL_SELECT,0,.016f,0,0);
 INPUT_CHECK(tracked_mission==0&&page==CAMPAIGN,"tracking: selecting the story replaces the welcome mission");
 TEST_INIT();game.job_n=2;game.jobs[0]=(Job){1,MISSION_DELIVERY,0,-1,1,7,1000,300};game.jobs[1]=(Job){2,MISSION_RESCUE,0,-1,1,7,2000,300};
 change_page(MISSIONLOG);row=3;input(PSP_CTRL_SELECT,0,.016f,0,0);
 INPUT_CHECK(tracked_mission==3&&game.job_sel==1&&page==CAMPAIGN,"tracking: Select synchronizes contract selection as well as the details page");
 change_page(MISSIONLOG);row=2;input(PSP_CTRL_TRIANGLE,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(game.job_n==1&&tracked_mission==2&&game.jobs[0].type==MISSION_RESCUE,"tracking: abandoning an earlier contract preserves the selected job after list compaction");
 row=2;input(PSP_CTRL_TRIANGLE,0,.016f,0,0);input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(game.job_n==0&&tracked_mission==0,"tracking: removing the tracked contract returns tracking to the story");
 TEST_INIT();page=CAMPAIGN;row=0;game.campaign_stage=1;campaign_screen();
 INPUT_CHECK(strstr(dialogue_source,"Choose Launch ship")!=0,"tracking: accepted First Flight explains the visible launch action");
 dump_native_bmp("tracking-first-flight-launch.bmp");
 input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!game.docked&&!(game.campaign_flags&CP_LOCKED),"tracking: launch does not pretend the player has locked the hub");
 game.campaign_stage=4;game.campaign_flags|=CP_FLEW;game.campaign_distance=600;change_page(CAMPAIGN);campaign_screen();
 INPUT_CHECK(strstr(dialogue_source,"Circle within 2,500")!=0&&strstr(narrative_label(narrative_action(CAMPAIGN)),"guidance")==0,"tracking: return step explains real docking controls without a guidance-menu detour");
 dump_native_bmp("tracking-first-flight-return.bmp");input(PSP_CTRL_CROSS,0,.016f,0,0);
 INPUT_CHECK(page==FLIGHT&&!game.dock_stage,"tracking: return-to-flight reply leaves docking under the player's control");
 TEST_INIT();tracked_mission=1;game.guild_chapter=1;page=CAMPAIGN;campaign_screen();dump_native_bmp("tracking-guild-next-step.bmp");
 TEST_INIT();game.job_n=MISSION_SLOTS;station_tour_stage=STATION_TOUR_ROUTE;page=MISSIONLOG;row=mission_log_count()-1;
 for(int i=0;i<MISSION_SLOTS;i++)game.jobs[i]=(Job){i,MISSION_DELIVERY,0,-1,1,7,1000,300};
 rect(0,0,W,H,BG);mission_log();dump_native_bmp("tracking-full-mission-log.bmp");
 INPUT_CHECK(mission_log_count()==8&&mission_track_at(row)==TRACK_STATION_TOUR,"tracking: full contract log still exposes the optional welcome mission");
 TEST_INIT();game.campaign_stage=6;game.saga_chapter=3;game.saga_step=1;game.saga_dest=7;page=CAMPAIGN;row=0;campaign_screen();
 input(PSP_CTRL_DOWN,0,.016f,0,0);INPUT_CHECK(row==0,"tracking: evidence delivery shows a next-step action before its three-way decision is available");
 TEST_INIT();tracked_mission=TRACK_STATION_TOUR;station_tour_stage=STATION_TOUR_ROUTE;game.system=STATION_TOUR_DEST;game.docked=1;game.station_variant=0;page=CAMPAIGN;station_tour_action();
 INPUT_CHECK(page==WALK&&station_tour_stage==STATION_TOUR_WALK,"tracking: a selected welcome mission can start when already docked at Reorte");
 TEST_INIT();page=HOME;row=17;rect(0,0,W,H,BG);home();dump_native_bmp("tracking-work-menu.bmp");
 TEST_INIT();page=HOME;
}
