/* Authored local conversations. These describe the existing objectives;
 * they never promise an unimplemented mission or award extra credits. */
static const char *ps_personal[12]={
 "People think supplies disappear because somebody steals them. Sometimes they do. More often, a tired person copies one digit badly and a crate spends a month visiting places that never ordered it. I put a paper label inside every lid now. Machines can argue with each other; a person opening the crate deserves a straight answer.",
 "The first expedition called this a monument. That sounded grand enough for their report, so the name stuck. I am not convinced. Look how low those markings begin. This might have been somewhere people worked, or waited for water. I would rather leave a question open than turn somebody's ordinary life into a legend by mistake.",
 "There is a little delay between seeing a ship's running lights and hearing its call. On a quiet shift, you begin to recognise the pilots by that pause. One always apologises to the equipment before transmitting. Another whistles. They probably think nobody notices. I would notice if either of them stopped coming through.",
 "I kept counting the beacon pulses because it gave the waiting a shape. After a while I couldn't remember whether a hundred pulses meant good news or just another hundred. Don't tell me everything is fine until the signal actually gets through. Just knowing somebody has found this place is enough for now.",
 "The first thing visitors ask is whether any of this can be eaten. Fair question, I suppose. But a plant can be useful without ending up on a plate. Some hold loose ground together; some tell us the water is changing. Those are the things I want in a field report. Not everything worth saving has a sale price.",
 "Someone once asked how much a complete skeleton would fetch. I told them an incomplete one, left where it was found, might teach us more. The surrounding layers matter. Where it fell matters. A beautiful specimen with no record of its home is still beautiful, but it has lost most of its story.",
 "When this place runs properly, nobody remembers it exists. I like that. Somewhere beyond the ridge a kettle boils, a room stays warm, and nobody has to think about the regulator. The difficult part is persuading people to maintain something before it starts making a noise they can hear from home.",
 "It was supposed to come back along the same route. There was nothing heroic in the instructions: take readings, avoid the ridge, return. I have stopped guessing what happened. The recorder may tell us. Until then, I would rather not blame the weather, the machine or whoever last serviced it.",
 "A distant shape isn't a species record. People get annoyed when I say that, but two animals can look alike and behave quite differently. Watch what it does when nothing is chasing it. Where it rests, what it avoids. The quiet observations are usually the ones another researcher can actually use.",
 "There is always someone who wants the largest crystal broken free. They imagine it shining on a shelf. I like it here, catching a different colour every time the light changes. Recording the faces gives us something useful without leaving a hole where the interesting part used to be.",
 "Most of these voices are talking about very ordinary things. A late delivery. A birthday. Somebody borrowing a tool and forgetting to return it. That is why I keep them. A settlement isn't only its founders and emergencies. People lived whole days between the events somebody thought to put in a history book.",
 "Pilots ask me whether the weather will be good. Good for whom? A grower wants moisture; a shuttle wants a clear approach; someone repairing an antenna wants neither rain nor wind. I give them measurements and let them argue about what counts as a pleasant afternoon. At least the instruments don't take it personally."
};
static const char *ps_secondary[12]={
 "The inventory terminal lists the crate's contents against a transfer reference. It is not a shop: there is no charge for recovering these expedition supplies. The limiting factor is room in your hold, and the manifest specifies one tonne of minerals.",
 "The survey desk holds a diagram of the stones with blank spaces for measurements. Previous visitors have left the originals undisturbed. Your contribution will be a record of the arrangement, not an artefact removed from the site.",
 "A thin trace crosses the signal display. Beside it, the reference channel stays steady. Comparing the two makes the receiver's drift apparent. The calibration controls are local; you do not need to buy a module to finish this work.",
 "The supply pack has been opened and carefully repacked. Its owner has been trying to make everything last. There is nothing here offered as salvage. The useful task is restoring the distress link, not taking what remains.",
 "The irrigation controls are marked in small, precise increments. A handwritten warning asks visitors not to adjust them by guesswork. The research request concerns your species records, not a mechanical fault in the watering system.",
 "The sample bench separates loose stone from labelled reference material. No one has asked you to dig anything out. Recording the exposed fossil is enough; a careful survey is more valuable than an unlabelled fragment in your hold.",
 "The gauge has a narrow marked operating band. Its needle has climbed beyond that band, but the casing is intact. The site's regulator can release the excess pressure as part of the maintenance task.",
 "The recorder sits in a protected compartment. Its housing took less of the impact than the outer frame. The survey assignment is to recover its stored route, not to repair the entire drone or claim it as a vehicle.",
 "The tracking desk compares sightings with field records. Empty entries do not mean there are no animals: they mean nobody has submitted a confirmed observation. Log one local animal before attempting the upload.",
 "The survey rig is aimed at the three nearest crystal faces. It measures them without cutting. The research payment is for a registered formation, so no spare cargo space is needed for this task.",
 "The cabinet's tapes still follow their original order. That gives the terminal a way to rebuild its damaged index. The recordings can remain here while their catalogue is restored for future visitors.",
 "The forecast desk displays the reference pressure beside the sensor reading. Their disagreement is why the array needs attention. Submitting the corrected measurement completes the local survey; it does not change the actual weather."
};
