static unsigned sector_hash(unsigned x){x^=x>>16;x*=0x7feb352du;x^=x>>15;x*=0x846ca68bu;return x^(x>>16);}
int prosperity(const Game *g,int system){const int wealth[8]={5,4,2,3,3,5,4,2};return wealth[g->systems[system].economy];}
void system_bodies(Game *g){
 const Vec3 positions[BODY_COUNT]={{18000,7000,42000},{-5000,2500,14000},{8500,-2000,23000},{-22000,-4000,38000},{12000,5000,-24000}};
 const float radii[BODY_COUNT]={4200,1700,1100,3600,1400};
 /* World-type order rotates per system so neighbouring stars don't share the same skyline. */
 const int world_cycle[4]={OCEAN,ROCKY,GAS,ROCKY};
 /* Eight stellar classes: amber, gold, red, blue-white, ice-blue, rose,
  * pale yellow and warm white. The system seed makes each sky memorable. */
 const unsigned suns[]={0x80dfff,0x66c8ff,0x526eff,0xf4f4ff,0xffc88a,0xc88cff,0x9ee8ff,0xd8e8ff};
 const unsigned worlds[]={0xc97535,0x91b45c,0x8763b5,0x7ebfc4,0xb87775,0xadc2ce,0xd4a574,0x5a8f6a,0x6b5b95,0xc45c5c};
 unsigned sys=sector_hash((g->system+1)*0x9e3779b9u);float system_scale=.72f+((sys>>8)%55)*.01f;float system_tilt=((int)((sys>>20)%3200)-1600)*.00012f;
 int type_rot=(int)((sys>>4)%4);
 for(int i=0;i<BODY_COUNT;i++){Body *b=&g->bodies[i];unsigned h=sector_hash((g->system+1)*911u+i*65537u);b->seed=h;b->pos=positions[i];float angle=(h%6283)*.001f+(sys%2400)*.001f+i*.21f+g->system*.07f;float radial=system_scale*(.82f+((h>>12)%40)*.01f);b->pos.x*=radial;b->pos.z*=radial;float c=cosf(angle),s=sinf(angle);b->pos=(Vec3){b->pos.x*c+b->pos.z*s,b->pos.y*radial+(int)((h>>18)%9000)-4500+system_tilt*b->pos.z,-b->pos.x*s+b->pos.z*c};b->radius=radii[i]*(g->system==7?1:.68f+((h>>12)%78)*.01f);b->type=i==0?SUN:world_cycle[(i-1+type_rot)&3];b->color=i==0?suns[h%8]:worlds[(h>>8)%10];b->accent=worlds[(h>>16)%10];if(g->system==7&&i==1){b->type=OCEAN;b->color=0xc35f23;b->accent=0x4b9137;}snprintf(b->name,sizeof(b->name),"%s %s",g->systems[g->system].name,i==0?"SUN":i==1?"I":i==2?"II":i==3?"III":"IV");}
}
int mission_destination(const Game *g,int offer){int n=0;for(int i=0;i<256;i++)if(i!=g->system&&distance_ly(g,g->system,i)<=10.0f){if(n++==offer)return i;}return -1;}
int mission_count(const Game *g){int max=1+prosperity(g,g->system),n=0;while(n<max&&mission_destination(g,n)>=0)n++;return n;}
int jobs_active(const Game *g){return g->job_n;}
int mission_type_for_offer(const Game *g,int offer){return (g->system+offer)%MISSION_TYPES;}
const char *mission_name(int type){static const char *names[]={"Food delivery","Pirate hunt","Exploration scan","Pilot rescue","Covert delivery"};return type>=0&&type<MISSION_TYPES?names[type]:"Unknown mission";}
const char *mission_brief(const Game *g,int offer){static char out[96];int type=mission_type_for_offer(g,offer),risk=danger_rating(g,g->system),wealth=prosperity(g,g->system);const char *dest=mission_destination(g,offer)>=0?g->systems[mission_destination(g,offer)].name:"nearby space";if(type==MISSION_DELIVERY)snprintf(out,sizeof(out),wealth>=4?"Fresh cargo to %s; market is hungry.":"Essential cargo to %s; margins are thin.",dest);else if(type==MISSION_BOUNTY)snprintf(out,sizeof(out),risk>=4?"Raiders active near %s; bounty is live.":"Track one wanted hull beyond %s.",dest);else if(type==MISSION_EXPLORATION)snprintf(out,sizeof(out),"Survey the unusual worlds around %s.",dest);else if(type==MISSION_RESCUE)snprintf(out,sizeof(out),risk>=4?"Distress beacon in hostile lanes near %s.":"A civilian beacon is waiting near %s.",dest);else snprintf(out,sizeof(out),"Quiet courier run to %s; local law is watching.",dest);return out;}
int mission_risk(const Game *g,int offer){int id=mission_destination(g,offer);if(id<0)return 1;int r=danger_rating(g,id);int type=mission_type_for_offer(g,offer);if(type==MISSION_BOUNTY||type==MISSION_SMUGGLING)r++;return r>5?5:r<1?1:r;}
int mission_reward(const Game *g,int offer){int id=mission_destination(g,offer),type=mission_type_for_offer(g,offer);if(id<0)return 0;const int bonus[]={0,700,500,900,1300};int risk=mission_risk(g,offer);return 1000+(int)(distance_ly(g,g->system,id)*200)+prosperity(g,g->system)*150+bonus[type]+(risk-1)*125;}
static int job_marked(const Job *j,const Game *g,int id){if(j->dest!=g->system)return 0;if(j->type==MISSION_DELIVERY||j->type==MISSION_SMUGGLING)return id==0;if(j->type==MISSION_EXPLORATION)return id==j->item+1;if(j->type==MISSION_RESCUE&&j->stage)return id==0;if((j->type==MISSION_BOUNTY||j->type==MISSION_RESCUE)&&j->target>=0)return id==BODY_COUNT+1+j->target;return 0;}
static void jobs_sync(Game *g){if(g->job_n<=0){g->job_n=0;g->job_sel=0;g->contract=-1;g->mission_target=-1;g->mission_stage=0;g->contract_time=0;g->contract_reward=0;return;}if(g->job_sel<0||g->job_sel>=g->job_n)g->job_sel=0;Job *j=&g->jobs[g->job_sel];g->contract=j->dest;g->mission_type=j->type;g->mission_stage=j->stage;g->mission_target=j->target;g->mission_item=j->item;g->mission_origin=j->origin;g->contract_reward=j->reward;g->contract_time=j->time;}
static void jobs_from_legacy(Game *g){if(g->job_n>0||g->contract<0)return;g->jobs[0].dest=g->contract;g->jobs[0].type=g->mission_type;g->jobs[0].stage=g->mission_stage;g->jobs[0].target=g->mission_target;g->jobs[0].item=g->mission_item;g->jobs[0].origin=g->mission_origin;g->jobs[0].reward=g->contract_reward;g->jobs[0].time=g->contract_time>0?g->contract_time:300;g->job_n=1;g->job_sel=0;}
static void job_remove(Game *g,int i){if(i<0||i>=g->job_n)return;for(int k=i;k<g->job_n-1;k++)g->jobs[k]=g->jobs[k+1];g->job_n--;if(g->job_sel>=g->job_n)g->job_sel=g->job_n-1;if(g->job_sel<0)g->job_sel=0;jobs_sync(g);}
static void mission_finish_slot(Game *g,int i,const char *notice){if(i<0||i>=g->job_n)return;guild_event(g,g->jobs[i].type==MISSION_DELIVERY?GUILD_DELIVERY:g->jobs[i].type==MISSION_RESCUE?GUILD_RESCUE:0);g->credits+=g->jobs[i].reward;g->mission_result=1;g->last_mission_type=g->jobs[i].type;g->last_mission_system=g->jobs[i].dest;job_remove(g,i);message(g,notice);}
void mission_timers(Game *g,float dt){if(g->docked||g->dead||g->police_stop||g->approach>=0||g->dock_stage||g->jump>0)return;jobs_from_legacy(g);for(int i=0;i<g->job_n;){g->jobs[i].time-=dt;if(g->jobs[i].time<=0){g->mission_result=-1;g->last_mission_type=g->jobs[i].type;g->last_mission_system=g->jobs[i].dest;char note[96];snprintf(note,sizeof(note),"Mission expired: %s.",mission_name(g->jobs[i].type));int crate=g->jobs[i].type==MISSION_DELIVERY?0:g->jobs[i].type==MISSION_SMUGGLING?6:-1;if(crate>=0&&g->cargo[crate]>0)g->cargo[crate]--;job_remove(g,i);message(g,note);}else i++;}jobs_sync(g);}
const char *mission_objective_at(const Game *g,int slot){static char out[96];if(slot<0||slot>=g->job_n)return "No active mission";const Job *j=&g->jobs[slot];if(g->system!=j->dest){snprintf(out,sizeof(out),"Jump to %s",g->systems[j->dest].name);return out;}if(j->type==MISSION_BOUNTY){snprintf(out,sizeof(out),"Destroy the marked pirate");return out;}if(j->type==MISSION_EXPLORATION){snprintf(out,sizeof(out),"Approach and scan %s",g->bodies[j->item].name);return out;}if(j->type==MISSION_RESCUE){snprintf(out,sizeof(out),j->stage?"Return the rescued pilot to the station":"Fly within 600 m, then press O");return out;}if(j->type==MISSION_DELIVERY){snprintf(out,sizeof(out),"Dock with the food crate still aboard");return out;}if(j->type==MISSION_SMUGGLING){snprintf(out,sizeof(out),"Dock. Keep the narcotics in the hold");return out;}snprintf(out,sizeof(out),"Dock at %s",station_name(g));return out;}
const char *mission_objective(const Game *g){return mission_objective_at(g,g->job_sel);}
int is_mission_target(const Game *g,int id){for(int i=0;i<g->job_n;i++)if(job_marked(&g->jobs[i],g,id))return 1;if(g->job_n==0&&g->contract>=0){Job tmp={g->contract,g->mission_type,g->mission_stage,g->mission_target,g->mission_item,g->mission_origin,g->contract_reward,g->contract_time};return job_marked(&tmp,g,id);}return 0;}
int mission_interact(Game *g,int id){int n=id-BODY_COUNT-1;if(n<0||n>=NPC_COUNT)return 0;for(int i=0;i<g->job_n;i++){Job *j=&g->jobs[i];if(j->type!=MISSION_RESCUE||j->stage||!job_marked(j,g,id))continue;if(length(sub(g->pos,g->npc[n].pos))>600){message(g,"Move within 600 m of the rescue target.");return 0;}j->stage=1;g->job_sel=i;jobs_sync(g);g->cue=SFX_SCAN;message(g,"Pilot aboard. Return to the local station.");return 1;}return 0;}
int mission_offer_active(const Game *g,int offer){int dest=mission_destination(g,offer),type=mission_type_for_offer(g,offer);if(dest<0)return 0;for(int i=0;i<g->job_n;i++)if(g->jobs[i].dest==dest&&g->jobs[i].type==type)return 1;return 0;}
int abandon_mission(Game *g,int slot){jobs_from_legacy(g);if(slot<0||slot>=g->job_n)return 0;g->mission_result=-1;g->last_mission_type=g->jobs[slot].type;g->last_mission_system=g->jobs[slot].dest;int crate=g->jobs[slot].type==MISSION_DELIVERY?0:g->jobs[slot].type==MISSION_SMUGGLING?6:-1;if(crate>=0&&g->cargo[crate]>0)g->cargo[crate]--;g->credits+=100;char note[96];snprintf(note,sizeof(note),"Abandoned: %s. Crate/deposit returned.",mission_name(g->jobs[slot].type));job_remove(g,slot);message(g,note);g->cue=SFX_UI;return 1;}
int accept_mission(Game *g,int offer){if(!g->docked){message(g,"Dock to accept mission work.");return 0;}jobs_from_legacy(g);if(g->job_n>=MISSION_SLOTS){message(g,"Mission log full (5/5). Complete a job first.");return 0;}int destination=mission_destination(g,offer);if(offer<0||offer>=mission_count(g)||destination<0)return 0;int type=mission_type_for_offer(g,offer);if(mission_offer_active(g,offer)){message(g,"Mission in progress.");return 0;}if(g->credits<100){message(g,"Contract deposit: 10 units.");return 0;}if((type==MISSION_DELIVERY||type==MISSION_SMUGGLING)&&cargo_used(g)>=cargo_capacity(g)){message(g,"Hold is full. Free a tonne first.");return 0;}g->credits-=100;Job *j=&g->jobs[g->job_n];
 /* Prefer a landable world at the destination; type rotation can make body 1 a gas giant. */
 int item=1;{unsigned sys=sector_hash((destination+1)*0x9e3779b9u);int type_rot=(int)((sys>>4)%4);const int world_cycle[4]={OCEAN,ROCKY,GAS,ROCKY};const int prefer[]={1,2,4,3};
  for(int i=0;i<4;i++){int b=prefer[(destination+i)%4];if(destination==7&&b==1){item=1;break;}if(world_cycle[(b-1+type_rot)&3]!=GAS){item=b;break;}}}
 j->dest=destination;j->type=type;j->origin=g->system;j->stage=0;j->target=-1;j->item=item;j->time=300;j->reward=mission_reward(g,offer);g->job_sel=g->job_n;g->job_n++;g->destination=destination;if(type==MISSION_DELIVERY)g->cargo[0]++;else if(type==MISSION_SMUGGLING){g->cargo[6]++;add_crime(g,1);}jobs_sync(g);char note[96];snprintf(note,sizeof(note),"%s accepted. Risk %d/5. Log %d/%d.",mission_name(j->type),mission_risk(g,offer),g->job_n,MISSION_SLOTS);message(g,note);g->cue=SFX_SELECT;return 1;}
static void npc_blueprint(Game *g,NPC *n,int i){
 const char *traders[]={"COBRA MK 3","PYTHON","BOA","TRANSPORTER","SHUTTLE","MORAY"};
 const char *pirates[]={"MAMBA","KRAIT","ASP MK 2","FER DE LANCE","SIDEWINDER","BUSHMASTER"};
 const char *explorers[]={"ADDER","GECKO","OPHIDIAN","CHAMELEON","COBRA MK 1","IGUANA"};
 int variant=(i*7+g->system)%6; n->freighter=i<36&&i%12==8;n->scale=1;n->freight_style=(g->system+i/12)%3;n->cruise=n->freighter?60+(sector_hash(g->system*71u+i)%41):650;n->health=n->freighter?900:n->role==LAW?110:80;
 if(n->freighter){n->role=TRADERS;n->mesh=mesh_id(i==20?"ANACONDA":"BOA");}
 else n->mesh=mesh_id(n->role==TRADERS?traders[variant]:n->role==PIRATES?pirates[variant]:n->role==LAW?"VIPER":explorers[variant]);
 n->radius=30;for(int j=0;j<meshes[n->mesh].vertices;j++)n->radius=fmaxf(n->radius,length(meshes[n->mesh].v[j])*n->scale);
 if(n->freighter)n->radius=length(freight_extent(n));
}
