/* Auto-generated by tools/bake-station-art.py — do not hand-edit.
 * ART DIRECTOR palette + room style kits (PR #11 handoff).
 * Optional include for station-crawl: #include "station-art-kit.h"
 * This file never owns crawl input/state — release agent wires it.
 */
#ifndef ELITE_STATION_ART_KIT_H
#define ELITE_STATION_ART_KIT_H

/* Shared McQuarrie / MacVenture palette */
#define ART_VOID RGB(8,13,24)
#define ART_CHARCOAL RGB(21,28,39)
#define ART_SLATE RGB(41,54,70)
#define ART_OLIVE RGB(90,96,76)
#define ART_RUST RGB(139,75,55)
#define ART_OCHRE RGB(193,139,77)
#define ART_CREAM RGB(229,210,163)
#define ART_LAVENDER RGB(155,154,165)
#define ART_CYAN RGB(85,212,212)
#define ART_AMBER RGB(240,180,91)
#define ART_DANGER RGB(200,90,75)

enum {
  ART_ROOM_HALL=0, ART_ROOM_HUB, ART_ROOM_SHOP, ART_ROOM_BAR,
  ART_ROOM_BAY, ART_ROOM_CLINIC, ART_ROOM_GUILD, ART_ROOM_CUSTOMS,
  ART_ROOM_COUNT
};

typedef struct {
  unsigned wall, wall2, trim, lamp, accent;
  const char *short_name;
  const char *keywords;
  const char *focus;
} ArtRoomStyle;

static const ArtRoomStyle art_room_styles[ART_ROOM_COUNT]={
  {RGB(41,54,70),RGB(21,28,39),RGB(90,96,76),RGB(240,180,91),RGB(85,212,212),"HALL","FAR DOOR / ROUTE","far hatch / route"},
  {RGB(21,28,39),RGB(41,54,70),RGB(229,210,163),RGB(193,139,77),RGB(85,212,212),"HUB","ARRIVALS / BERTH","arrivals board / berth window"},
  {RGB(41,54,70),RGB(21,28,39),RGB(193,139,77),RGB(240,180,91),RGB(85,212,212),"SHOP","PARTS / COUNTER","parts counter"},
  {RGB(90,96,76),RGB(21,28,39),RGB(139,75,55),RGB(240,180,91),RGB(193,139,77),"BAR","RUMOUR / PASSENGER","service counter"},
  {RGB(41,54,70),RGB(21,28,39),RGB(193,139,77),RGB(240,180,91),RGB(85,212,212),"BAY","CRATES / LIFT","cargo lift / crate lane"},
  {RGB(41,54,70),RGB(21,28,39),RGB(155,154,165),RGB(85,212,212),RGB(229,210,163),"CLINIC","MEDIC / BENCH","treatment bench"},
  {RGB(90,96,76),RGB(21,28,39),RGB(229,210,163),RGB(240,180,91),RGB(85,212,212),"GUILD","EVIDENCE / DESK","evidence / survey desk"},
  {RGB(21,28,39),RGB(8,13,24),RGB(200,90,75),RGB(240,180,91),RGB(85,212,212),"CUSTOMS","SCAN / LAW","scanner gate"},
};

/* Map existing SC_ROOM_* enums → art style index. Returns -1 if unknown. */
static int art_style_for_sc_room(int sc_room){
  switch(sc_room){
  case 0: return ART_ROOM_HALL; /* SC_ROOM_EMPTY */
  case 1: return ART_ROOM_HUB;
  case 2: return ART_ROOM_SHOP;
  case 3: return ART_ROOM_BAR;
  case 4: return ART_ROOM_BAY;
  case 5: return ART_ROOM_CLINIC;
  case 6: return ART_ROOM_GUILD;
  case 7: return ART_ROOM_CUSTOMS; /* SC_ROOM_LOCK */
  default: return -1;
  }
}

static const ArtRoomStyle *art_room_style(int art_id){
  if(art_id<0||art_id>=ART_ROOM_COUNT)return &art_room_styles[ART_ROOM_HALL];
  return &art_room_styles[art_id];
}

/* Economy flavour nudges (optional). agri=1 boosts bay/bar warmth; industrial boosts shop/trim. */
static unsigned __attribute__((unused)) art_econ_trim(unsigned base,int economy){
  if(economy>=4) return base; /* agri — keep ochre/rust warmth */
  /* industrial — pull trim toward slate/cyan slightly via mix in caller */
  return base;
}

#endif /* ELITE_STATION_ART_KIT_H */
