/* First Light: optional, ordered, event-driven tutorial. Stable append-only save IDs. */
#ifndef ELITE_TUTORIAL_H
#define ELITE_TUTORIAL_H
enum { TU_LAUNCH, TU_YAW, TU_PITCH, TU_THROTTLE, TU_BRAKE, TU_ROLL, TU_BOOST, TU_PIP, TU_LOCK, TU_VIEW, TU_DOCK, TU_SAVE, TU_SELL, TU_BUY, TU_FIT, TU_NET, TU_TALK, TU_SHOP, TU_GUILD, TU_FIRE, TU_SALVAGE, TU_SCAN, TU_FUEL, TU_JUMP, TU_ATMOSPHERE, TU_LAND, TU_EVA, TU_SURVEY, TU_BOARD, TU_ORBIT, TU_FINISH };
typedef struct { const char *title,*speaker,*copy,*task; int event,arg,unlock; } TutorialBeat;
static const TutorialBeat tutorial_beats[]={
 {"THE EMPTY BERTH","KEI","Ryn left her kettle on. Search Control calls that irrelevant. I call it a reason to keep looking. Before I give you her route, I need to know you can come home. Venn has lent us an Adder and cleared a practice lane. One switch first. The rest can wait.","FLY > Launch. Press X.",TU_LAUNCH,0,0},
 {"A SMALL CORRECTION","VENN","Tower here. Kei tells everyone I am strict. I prefer 'predictably disappointed'. Nudge the nose left or right with the D-pad or nub. Watch the stars move. Small corrections; you are steering a ship, not stirring soup.","D-pad LEFT/RIGHT or nub: turn for 1 second.",TU_YAW,0,-1},
 {"ABOVE AND BELOW","VENN","Good. Now raise or lower the nose. Keep the hub out of your path while you practise. Space has no floor, but stations are remarkably committed to having walls.","D-pad UP/DOWN or nub: pitch for 1 second.",TU_PITCH,0,-1},
 {"A LITTLE MOMENTUM","KEI","Ryn used to say engines sound different when you stop being afraid of them. I think she meant practise. Hold R and watch your speed rise. Release it when you are comfortable; the ship keeps moving.","Hold R until speed reaches 150.",TU_THROTTLE,0,-1},
 {"THE MOST USEFUL BUTTON","VENN","And now the skill that saves more pilots than marksmanship: slowing down. Hold L until the speed display drops below forty. There is no prize for reaching the berth before your brakes.","Hold L. Slow below 40.",TU_BRAKE,0,-1},
 {"THE LITTLE BLUE WORLD","KEI","Roll changes the view, not which way your steering works. Hold L with Left or Right briefly. Ryn rolled every time she saw an ocean. She called it waving. Please do not wave inside the station.","Hold L + LEFT/RIGHT to roll for 1 second.",TU_ROLL,0,-1},
 {"BORROWED SPEED","VENN","Double-tap R, holding the second tap, for boost. Then let go. Heat climbs quickly; boosting hot drains shields and damage means an engineer's bill. This is a short test, not an invitation to discover your insurance limits.","Double-tap R; hold the second tap briefly.",TU_BOOST,0,-1},
 {"THREE WAYS HOME","KEI","Hold Start to pause and move power between SYS, ENG and WEP. Left/Right chooses a bank; Up/Down moves a pip. SYS supports shields, ENG supports engines, WEP supports weapons. Spend power on what you need now.","Hold START; select a bank and move a pip.",TU_PIP,0,-1},
 {"FIND THE LIGHTHOUSE","VENN","Hold Square for the targeting computer. Left/Right changes category; Up/Down chooses a contact. Find the station. While still holding Square, press R to lock it. Auto-turn points the nose for you; manual steering takes control back.","Hold SQUARE, choose STATION, then press R.",TU_LOCK,0,8},
 {"A CHANNEL WITH A PURPOSE","KEI","Select opens your paused command deck. Comms is now available under FLY. It can request docking, open radio settings and hail a target. Routine chatter is information, not homework. Open Comms, read the options, then Circle back.","SELECT > FLY > Comms panel. Read; O back.",TU_VIEW,10,10},
 {"COME HOME BORING","VENN","Keep the hub selected and approach slowly. Circle near the hub requests guided docking; Comms also has a docking request. If you are too far away, close the distance first. Let the arrival sequence finish. I will complain about your parking only after you survive it.","Face the hub, approach, press O. Finish docking.",TU_DOCK,0,-1},
 {"THE BORROWED SHIP","KEI","That was a landing, not a promise. Good. The Guild has released 500 units for training expenses. Before we spend them, open Save / status. Records tell you what you own and what the local law thinks of you. Tutorial saves use their own file.","COMMANDER > Save / status. Read; O back.",TU_VIEW,5,5},
 {"WRITE IT DOWN","VENN","A memory stick is more reliable than a pilot saying 'I will remember'. Open Save / status and press X to save while docked. We also checkpoint completed dockside lessons. Your normal commander has a separate file.","Save / status: X SAVE while docked.",TU_SAVE,0,-1},
 {"TWO TONNES OF BREAKFAST","KEI","I put two tonnes of food in the hold. No, it is not all for you. Sell one unit of Food at Cargo & market with Left. Prices are per unit; restricted goods bring law attention. A contract's reserved cargo cannot be sold out from under it.","SHIP > Cargo & market. FOOD: LEFT to sell 1.",TU_SELL,0,1},
 {"A RECEIPT, NOT A FAVOUR","KEI","Now buy one unit of Food back with Right. Check the balance and hold space. Trading is real even during training. A passenger also needs hold room; fuel is kept separately. Ryn always checked her receipts. We will need that habit.","Cargo & market. FOOD: RIGHT to buy 1.",TU_BUY,0,-1},
 {"SIX PLACES FOR TROUBLE","VENN","Open Ship loadout. WPN, DEF, NAV, HOLD, FUEL and UTIL each take one fitted module. Replacing a module gives up its old effect. Removing a hold expansion is refused if the cargo will not fit. Inspect a slot, then come back.","SHIP > Ship loadout. Inspect slots; O back.",TU_VIEW,21,21},
 {"TOOLS BEFORE HEROICS","KEI","Open Outfitting and fit a Pulse Laser. The training allowance covers it. Select the actual item and press X; the receipt shows the cost. Equipment stock varies between stations. We are fitting a tool for controlled practice, not buying permission to shoot strangers.","SHIP > Outfitting. Select PULSE LASER; X.",TU_FIT,1,4},
 {"THE ENGINEER'S INVOICE","VENN","Engineers repair persistent ship damage for a fee. Shields recovering does not mend a damaged hull. Smoke, shaking and poor performance are reasons to visit. Read your condition and quote. We will not break the ship just to demonstrate the bill.","SHIP > Engineers. Inspect condition; O back.",TU_VIEW,24,24},
 {"SOMETHING THAT IS YOURS","KEI","Ryn painted a small blue stripe on every ship she flew. Said the galaxy was too large to leave everything anonymous. Ship decorator previews finishes before you pay. Browse them. Buying paint is optional; your next meal is not.","SHIP > Ship decorator. Browse; O back.",TU_VIEW,23,23},
 {"THE PRICE OF A BIGGER HOLD","VENN","Shipyard exchanges your current hull. Compare hold, speed, range and the exchange price. Your cargo must fit the replacement. Modules transfer, and excess fuel is capped to the new tank. Browse the ships; you do not need to buy one for this lesson.","SHIP > Shipyard. Compare hulls; O back.",TU_VIEW,3,3},
 {"THE ROOM WE LIVE IN","KEI","The receipt from Ryn's last resupply says Lave. That gives us a place, not a culprit. System details lists the hub, worlds, economy and local risk. Open it and read the room before we start accusing the furniture.","FLY > System details. Read; O back.",TU_VIEW,11,11},
 {"COLOURS ARE NOT MOTIVES","KEI","Factions tells you who shares the lanes: traders, law, pirates and the Explorers Guild. A colour is a role, not a biography. Ryn once trusted a pirate's weather report and distrusted a Guild accountant. She was right both times.","WORK > Factions. Inspect a faction; O back.",TU_VIEW,7,7},
 {"THE PUBLIC VERSION","KEI","GalacticNet is the station's public memory. NEWS is what happened, or what someone wants recorded. Use L/R to change its tabs. Read a news item, then press Circle to finish each network lesson. We will compare six different kinds of evidence.","DISCOVER > GalacticNet. NEWS tab; O back.",TU_NET,0,14},
 {"THE PRICE OF A RUMOUR","KEI","MARKET is useful context, not a guaranteed profit. Prices change between systems; cargo space, legality and fuel all belong in the calculation. Ryn's food receipt looks ordinary. That is why someone missed it.","GalacticNet: L/R to MARKET. Read; O back.",TU_NET,1,-1},
 {"FACES ON THE BOARD","VENN","WANTED lists people the law is looking for. Read before acting; random violence earns your own notice. A poster is not a firing solution. This lesson is reconnaissance, and every civilian in my lane would like it to stay that way.","GalacticNet: L/R to WANTED. Read; O back.",TU_NET,2,-1},
 {"THE LAST ORDINARY POST","KEI","Open SPACEBOOK. People post jokes, warnings and small things that later become important. I have pinned Ryn's last receipt here. It says: 'If I miss supper, ask who kept the light on.' Read the post; X likes it, Triangle opens comments.","GalacticNet: SPACEBOOK. Read; try X; O back.",TU_NET,3,-1},
 {"PEOPLE, NOT MARKERS","KEI","INBOX holds local messages. Read the sender and the request before acting. Its social buttons are presentation, not mission acceptance; real contracts belong on the Mission board. Named travellers can also meet you out in space. People leave traces in other people\'s routines.","GalacticNet: L/R to INBOX. Read; O back.",TU_NET,4,-1},
 {"THE COST OF A NAME","VENN","JOBS is the mission feed: active work, outcomes and station offers. It tells you what is happening; Mission board is where you sign up and Mission log is where you track it. Read the feed, then we will meet the people behind these screens.","GalacticNet: L/R to JOBS. Read; O back.",TU_NET,5,-1},
 {"FEET ON THE DECK","KEI","Disembark from FLY. The station is more than a vending machine with an airlock. Up/Down chooses an option and X acts; doors, people and objects are listed. Circle or Triangle brings you back aboard. Find Venn in Arrivals and hear him out.","FLY > Disembark. VENN: choose first reply.",TU_TALK,0,20},
 {"THE THINGS OFF THE CATALOGUE","VENN","The chandlery stocks things the main outfitting board does not. From Arrivals take the SHOP door, talk to the Chandler and browse the exclusive stock. Opening a conversation does not commit you to a purchase.","SHOP > CHANDLER > Browse exclusive stock.",TU_SHOP,0,-1},
 {"THE LOADER'S LEDGER","KEI","From the shop, go to CARGO. Talk to the Loader and hear the first reply. Small paid favours live here too. His manifest puts Ryn's last crate on a survey run, not a smuggling run. That matters to me more than I expected.","CARGO BAY > LOADER > first reply.",TU_TALK,3,-1},
 {"SOMEONE REMEMBERS","KEI","Take the CANTEEN door. Ask the Bartend for a rumour. Passengers also look for lifts here; a taxi booking needs a fitted cabin and spare hold capacity. Today we need testimony. We are buying neither a drink nor a passenger's life story.","CANTEEN > BARTEND > first reply.",TU_TALK,2,-1},
 {"THE DESK WITH MY NAME","KEI","Return through Arrivals to the GUILD DESK. I am the one pretending paperwork is useful camouflage. Hear me out. Ryn went to check an old survey beacon. The rumour was that it still broadcast after its power supply was removed.","ARRIVALS > GUILD > KEI > first reply.",TU_TALK,4,-1},
 {"PUT YOUR OWN OXYGEN FIRST","VENN","The Guild passage leads to the MED CLINIC. Talk to the Medic. One-time supplies are exactly that: one time. Surface exploration has a return journey, and a clever discovery is no consolation to an empty suit.","GUILD > CLINIC > MEDIC > first reply.",TU_TALK,5,-1},
 {"A CLEAN MANIFEST","VENN","The clinic connects to CUSTOMS. Speak to the officer. Restricted cargo can trigger a scan; refusing law carries consequences. Do not accept an illicit job because the pay is printed in a cheerful colour. Return aboard when you are done.","CLINIC > CUSTOMS > officer > first reply.",TU_TALK,6,-1},
 {"WORK THAT KEEPS YOU FLYING","KEI","Back aboard, open Mission board. Read a brief: destination, objective, time and payment. Delivery, rescue, exploration, bounty and smuggling ask different things. Accepting is optional here. I will not make you sign a dangerous contract to pass a reading lesson.","O aboard > WORK > Mission board. Read; O back.",TU_VIEW,12,12},
 {"ONE PROMISE AT A TIME","KEI","Mission log keeps accepted jobs, Guild work and the main story together. X tracks an entry; Select opens its next step. Timers pause while you read menus. Review the log, then back out. Tracking a task is a reminder, not teleportation.","WORK > Mission log. Review entries; O back.",TU_VIEW,13,13},
 {"THE LONGER ROAD","KEI","Tracked mission carries Open Channel, the larger story of Ryn's disappearance. This training is the beginning of your life here, not the solution to her case. Read the briefing and return. We will leave its choices for after your licence.","WORK > Tracked mission. Read; O back.",TU_VIEW,17,17},
 {"THE GUILD'S OTHER PROMISES","KEI","Guild assignments are listed beside our main story in Mission log. Highlight Explorers Guild and press X to track it. Tracked Mission will then show the next step for that assignment. You can switch back to our story in the same way.","WORK > Mission log > Explorers Guild. X to track.",TU_GUILD,0,13},
 {"KEEP THE VIEW YOURS","VENN","Display & chatter includes HUD layout, quiet text, contrast and third-person view. Set what helps you see. Essential safety prompts remain. This is your cockpit; comfort is equipment too.","COMMANDER > Display & chatter. Review; O back.",TU_VIEW,19,19},
 {"THE VOICES BETWEEN STARS","KEI","Radio & audio gives you music, chatter and separate volume controls. L/R tunes stations; Left/Right adjusts the selected volume; Triangle turns radio on or off. Pick something you like. Silence is an option too.","COMMANDER > Radio & audio. Tune; O back.",TU_VIEW,16,16},
 {"A REFERENCE, NOT AN EXAM","VENN","Controls keeps five reference pages, including targeting, travel, station menus and surface movement. Left/Right changes pages. L toggles analog steering if the nub is drifting. You can always come back here.","COMMANDER > Controls. Browse pages; O back.",TU_VIEW,6,6},
 {"THE TEST OUTSIDE THE WINDOW","KEI","Launch again. Venn has put a harmless practice canister outside the flight lane. We will learn what the ship can do away from other people's paintwork. Your laser stays cold until I say where to point it.","FLY > Launch.",TU_LAUNCH,0,-1},
 {"A WEAPON IS A RESPONSIBILITY","VENN","Point into empty space, away from the hub and traffic, then press X for a short laser burst. L+X launches a missile at a locked hostile; we will not practise that on a neighbour. Empty WPN slots cannot fire. Watch the heat gauge.","Face empty space. Tap X to fire the fitted laser.",TU_FIRE,0,-1},
 {"THE THING YOU CAN BRING BACK","KEI","That blue canister ahead is ours: one sealed ration crate, placed for training. It is already selected. Circle within 500 metres starts the tractor. Let it finish. Ordinary salvage can contain restricted goods; a full hold may sell salvage automatically.","Practice canister selected. O; wait for tractor.",TU_SALVAGE,0,-1},
 {"A SIGNAL, NOT A GHOST","KEI","I have marked a calibration echo ahead. Circle within 1,100 metres scans it. This one is a training beacon, not Ryn. Learn the difference between collecting evidence and wanting an answer so badly that any light looks like one.","Calibration echo selected. Press O to scan.",TU_SCAN,0,-1},
 {"A RECORD THAT CAN BE CHECKED","KEI","Select pauses flight. Discovery Codex keeps visited systems and scanned life, minerals and anomalies. Find the new entry. The training echo is ordinary. That is useful: now you know what ordinary looks like.","SELECT > DISCOVER > Discovery Codex. O back.",TU_VIEW,15,15},
 {"HISTORY HAS MARGINS","KEI","Galactic Lore is the archive of eras, peoples and powers. Use L/R for categories and Up/Down for entries. It gives the rumours context; it does not prove them. Ryn used to write questions in the margins. I saved those pages.","DISCOVER > Galactic Lore. Browse; O back.",TU_VIEW,22,22},
 {"FUEL BEFORE DISTANCE","VENN","Return to the hub before the navigation lesson. Use your target browser to select the station, Square+R to align, then approach and Circle for docking. We check the tank on the ground, where mistakes are cheaper.","Select station. Approach; O to dock.",TU_DOCK,0,-1},
 {"FILL THE TANK","VENN","Outfitting's first entry refuels to your ship's range limit. Press X on it. A full tank already meets the check. The price is for missing fuel; fuel never consumes cargo tonnes. Do this before choosing a star.","SHIP > Outfitting > REFUEL; X.",TU_FUEL,0,-1},
 {"ONE STAR AT A TIME","KEI","Galaxy map has a nearby list and a full map. Triangle switches them. On the full map, X plots a route; on the nearby list, X launches the selected jump. Choose a reachable nearby system. We are testing navigation, not chasing Ryn beyond our fuel.","FLY > Galaxy map. Nearby reachable system: X.",TU_JUMP,0,2},
 {"ARRIVAL IS NOT THE END","VENN","Hyperspace leaves you outside the local hub. That is deliberate: nobody wants a visitor materialising in their kitchen. Find the station, close the distance and dock. A route can need several jumps, with refuelling between them.","Target local station. Approach; O to dock.",TU_DOCK,0,-1},
 {"THE SURVEYOR'S HABIT","KEI","One final field exercise: a landable world. We will launch, choose a non-gas planet, approach within 1,000 metres of its surface and press Circle. X accepts atmospheric entry. I have authorised the landing kit. The ground deserves patience.","Launch. Target non-gas planet; near surface O, X.",TU_ATMOSPHERE,0,-1},
 {"A PLACE TO SET DOWN","VENN","In atmosphere, Square points you toward the cyan landing pad. Reduce speed and get low over it; Circle lands when the approach is safe. Too high or too fast gives advice, not a pass. You can reread this lesson from the paused deck.","SQUARE finds pad. Fly low and slow; O lands.",TU_LAND,0,-1},
 {"LEAVE FOOTPRINTS","KEI","Circle leaves the landed ship. The D-pad walks and strafes; the nub looks. Hold L with the D-pad to look without moving. R is your jet lift; release it to descend. Keep the ship in sight. It is your way home.","Landed: O to leave ship. Walk a few steps.",TU_EVA,0,-1},
 {"FIRST LIGHT","KEI","Square surveys nearby unrecorded life or minerals. Move closer if nothing is in range. This is a real discovery, written to the same Codex as every other survey. Whatever happens to Ryn's case, today somebody looked carefully at this world. You did.","On foot: approach life or minerals; SQUARE scans.",TU_SURVEY,0,-1},
 {"THE RETURN HALF","VENN","Triangle faces the ship. Walk back close to it, settle onto the ground, then Circle boards. Jet lift helps with rough terrain, but you must come down to board. A survey is not finished until its pilot is aboard.","TRIANGLE faces ship. Walk close; O boards.",TU_BOARD,0,-1},
 {"LOOK BACK ONCE","KEI","Triangle takes off from the pad. Once airborne, Triangle returns to orbit; dismiss any active speech first. I used to think Ryn's courage was leaving. Now I think it was always expecting to return.","TRIANGLE takes off; TRIANGLE again to orbit.",TU_ORBIT,0,-1},
 {"A BERTH WITH YOUR NAME","VENN","One last dock. There is no timer and no bonus for speed. Use the tools you have learned. When you arrive, we will save your record and stop hiding the rest of the deck. You have earned the right to choose your own next mistake.","Target station. Approach; O to dock.",TU_DOCK,0,-1},
 {"THE MAINTENANCE HATCH","VENN","One final menu: Debug tools. These are development controls that change cash and world state. They are not paid station services or part of earning your licence. Inspect the list without activating anything, then return. In ordinary play they are entirely optional.","COMMANDER > Debug tools. Read only; O back.",TU_VIEW,9,9},
 {"THE LIGHT STAYS ON","KEI","Venn has signed your licence. The loader kept the receipt; the bartender kept a chair; I kept the channel. That is what Ryn meant about the light. We still do not know where she is. But now you can follow the evidence and come home with it. Open Channel awaits in Tracked mission.","X completes training. Every service opens.",TU_FINISH,0,-1},
};
#define TUTORIAL_COUNT ((int)(sizeof(tutorial_beats)/sizeof(tutorial_beats[0])))
static inline int tutorial_active(const Game *g){return g->tutorial_step>0&&g->tutorial_step<=TUTORIAL_COUNT;}
static inline const TutorialBeat *tutorial_beat(const Game *g){return tutorial_active(g)?&tutorial_beats[g->tutorial_step-1]:0;}
static inline int tutorial_service(const Game *g,int id){
 if(!tutorial_active(g))return 1;
 if(id==0)return 1;
 for(int i=0;i<g->tutorial_step;i++)if(tutorial_beats[i].unlock==id)return 1;
 return 0;
}
static inline int tutorial_event(Game *g,int event,int arg){
 const TutorialBeat *b=tutorial_beat(g);
 if(!b||g->tutorial_seen!=g->tutorial_step||b->event!=event||b->arg!=arg)return 0;
 g->tutorial_step++;g->tutorial_seen=0;return 1;
}
#endif
